### ISSUE TITLE
Allow for using meta rule's parameters in the meta rule's attributes

### ISSUE THREAD

**Issue by calexHG** [JetBrains/Grammar-Kit#100]
I'm starting to understand how more things work in Grammar-Kit. The `pin` and `recoverWhile` handling is starting to make sense finally after very slowly reading through the somewhat dense parser behind-the-scenes code (I was going to say "the somewhat dense parser backend code" but the word backend too overloaded).

So with this novice level of understanding, due to the way that recovery works, I found myself wanting to try out tricks like the following:

```
private meta withPassedRecovery
  ::= <<param1>>
    {
        recoverWhile = <<param2>>
    }
```

If one rule is used from different contexts, and in one or more of those contexts it would be suitable for that rule to use recovery, I thought it would make more sense to be able to define the recovery logic at the point of the actual rule call (where what the rule is being followed by is actually known) rather than inside the rule being called.

Alas that method of doing such a thing isn't supported though. My other unsupported experiments were things like this:
```
private meta withAutoRecovery
  ::= <<param1>>
    {
        recoverWhile = "#auto"
    }
```
and something else that I quickly realized might not even be possible to be written quite as simply, but it's idea was to turn the very simple but inefficient pattern used in my very first, just-get-it-working recovery rule (a simple not-predicate of the actual rule being recovered from) into a reusable pattern via a so-called "withReflectivelyDefinedRecovery" macro.

Naturally, it's not mandatory (see below) for any of these tricks to be supported, but it would be cool if they were. And isn't this the kind of stuff what meta was intended for?

_For now what I'm doing is, at the point of the rule call, defining a specialization of the rule being called:_
```
CallerRuleName
  ::= SOME_TOKEN_A CallerRuleName_CalleeRuleName+ SOME_TOKEN_B

private CallerRuleName_CalleeRuleName 
  ::= CalleeRuleName
    {
        // I just discovered auto, so I'm trying it out
        // instead of a simple brute-forced !CalleeRuleName recovery rule
        recoverWhile = "#auto"
    }

// ... close your eyes and imagine that there are 
// many many 10's of pages worth of unrelated 
// grammar in between the caller above and 
// the callee below ...

CalleeRuleName
  ::= OneOfManyDeepOptionsThatMightNotBePracticalToManuallyAnalyzeForAManuallyWrittenRecoverRule
    | ComplexOption2
    | ...
    | ComplexOption14

// ... close your eyes and imagine that there are 
// many many 10's of pages worth of unrelated 
// grammar in between the caller below and 
// the callee above ...

OtherCallerThatDoesntAsEasilyLendItselfTowardsSupportingRecoverWhile
  ::= CalleeRuleName SomeOtherRule
    | CalleeRuleName SomeOtherRule2
    | SomeOtherRule3
    | ... more definitions...

// ... much unrelated grammar ...

OtherOtherCallerThatDoesntAsEasilyLendItselfTowardsSupportingRecoverWhile
  ::= CalleeRuleName SomeOtherRule
    | CalleeRuleName SomeOtherRule2
    | SomeOtherRule3
    | ... more definitions...
```

_(I'm literally only just now playing with error-recovery, so it's entirely likely that I'll realize none of these patterns make sense for real use)_

**Comment by calexHG** [comment]
Oh. Wait a minute... It wasn't that I was using #auto from within a meta rule (see the second code block in my original post) that caused it not to work; it's that #auto itself that just isn't working, even from normal rules:
```
  final static Parser RuleNameHere_auto_recover_ = new Parser() {
    public boolean parse(PsiBuilder builder, int level) {
      return !nextTokenIsFast(builder, ); // <--- NOTE THE LACK OF A SECOND ARG
    }
  };
```
I originally thought that was just a limitation on what you could do with meta rules...

**Comment by gregsh** [comment]
I've come across a nice use-case for that on my own journey.
Sample:
````
meta abc ::= <<param>> {recoverWhile="<<recover>>"}
````
