### ISSUE TITLE
Allow non-positional pin syntax to target string literals

### ISSUE THREAD

**Issue by calexHG** [JetBrains/Grammar-Kit#102]
If one would like to change rules of this form:
```
FooBarStatement
  ::= Foo L_PAREN FooParamA SEMICOLON FooParamB R_PAREN Bar
  { pin="R_PAREN" }
```
Into rules that use string literals as pretty placeholders for their TokenType constants, it seems that a roadblock is hit, requiring either: no change at all; resorting to brittle, position-based pinning; or worse— an ugly hybrid approach:
```
{
    L_PAREN="("
    R_PAREN=")" 
}

FooBarStatement
  // I'd rather not change the rule at all than do something lopsided like this
  ::= Foo "(" FooParamA ";" FooParamB R_PAREN Bar
  { pin="R_PAREN" }
```
Or is there another solution?

## Feature request
Allow non-positional pin syntax to target string literals

### One more-than-acceptable path: 
As a targeted solution to the use case at hand (pinning string literals that are being used as stand-ins for known token constants), I expect that you could process token substitution before processing pin matching, allowing for a hybrid solution to the issue as a compromise that few could argue against:
```
{
    L_PAREN="("
    R_PAREN=")" 
}

FooBarStatement
  ::= Foo "(" FooParamA ";" FooParamB ")" Bar
  { pin="R_PAREN" }
```

### A more involved solution I don't currently have use for: 
Arbitrary matching against BNF rule definition source-text.

```
{
    L_PAREN="("
    R_PAREN=")" 
}

FooBarStatement
  ::= Foo "(" FooParamA ";" FooParamB ")" Bar
  { pin="\")\"" }
```
---
As always, thanks for the awesome tool. :heart:

**Comment by gregsh** [comment]
Hi @calexHG 
"The more involved solution" is already there, one just has to escape parenthesis as well (Java RegExp syntax..). So the following works as you wish:
````
FooBarStatement
  ::= Foo "(" FooParamA ";" FooParamB ")" Bar
  { pin="\"\)\"" }
`````

**Comment by calexHG** [comment]
Nifty. Got it. Thanks for the quick reply.

**Comment by calexHG** [comment]
I'm finding the toolkit is niftier than the docs reveal in more than one area..

Recently I noticed a JetBrains project using a `methods` PSI-accessor definition that at least appeared to be referencing a grammar component that wasn't even mentioned directly in the rule the `methods` definition was being applied to, but instead something that was likely a deeply nested subcomponent of a subcomponent of a subcomponent of one of the rules the current rule was composed of. If that's right, it seems to imply the `/expr[0]` syntax is more robust than the examples let on and that it might support more complicated XPath-like queries (`//` for descendents, rather than just `/` for direct children, and maybe even chained queries evaluated on top of one another like `/expr//foo[1]/bar`)?

**Comment by gregsh** [comment]
Just checked that I've forgot to mention that in 'methods' attribute documentation.
Did you find that you can do QuickDocumentation (Ctrl-Q/Ctrl-J) on attributes?

The path is /-separated list of items. Item is:
* the name of a rule or a token
* name[index], index=number, 'first' or 'last'

'//' is not supported, but now it can be easily implemented via SyntaxTraverser API
