### ISSUE TITLE
Please update plugin to get jflex-1.7.0-SNAPSHOT.jar

### ISSUE THREAD

**Issue by eprst** [JetBrains/Grammar-Kit#103]
Looks like jflex-1.4 was removed, now an attempt to run JFlex generator fails with this:

Failed to download 'https://github.com/JetBrains/intellij-community/raw/master/tools/lexer/jflex-1.4/lib/JFlex.jar':
Connection failed with HTTP code 404

**Comment by LichFaker** [comment]
+1

**Comment by gregsh** [comment]
https://github.com/JetBrains/Grammar-Kit/releases/tag/1.3.1

**Comment by eprst** [comment]
1.3.1 is since-build=146, which is not even in EAP

**Comment by gregsh** [comment]
my bad, now it's 143.
