### ISSUE TITLE
PSI element constructor customization

### ISSUE THREAD

**Issue by calexHG** [JetBrains/Grammar-Kit#105]
Is it currently possible to customize the constructors of the generated PSI classes, or can one not directly use Grammar-Kit for PSI classes that have different constructor requirements?

**Comment by gregsh** [comment]
ASTNode constructor is accompanied by Stub<T> constructor if 'stub' attribute is specified for a rule.
That's it. One can customize token factories/constructors but not PSI.

Should not be useful because parser can pass information to PSI only via IElementTypes.
Some API clients do not create PSI at all.

**Comment by calexHG** [comment]
Oh, nah, trust me, it it would be very useful for the roomful of people that are using the less well-known-about features of the Platform.

..My IDE in development would greatly benefit.

If I wanted to customize GK to perform nearly identical behavior to what you've explained it does with StubBasedPsiElementBase for another class, what would be involved? (What sections of codebase should be modified, and what, if anything, should I beware of)

**Comment by calexHG** [comment]
(Also-- not that it's really the path I'd prefer to take-- but just in seeing how well the alternative option of just keeping just the problematic PSI class out of GK's control goes... the answer seems to be: unexpectedly bumpy. Neither `generatePsi=false` nor `generate=[psi="no"]` get respected by GK when applied to an individual rule.)

**Comment by gregsh** [comment]
Can I see a sample of what you'd like to be generated?

**Comment by calexHG** [comment]
Well, I just successfully wrote a simple modification to get what I wanted working. Originally I envisioned GK just pulling in whatever constructor signatures were available in the defined superclass, but I haven't slept in almost 24 hrs, so I just did whatever required the least amount of typing ;]

```
SampleLazyCodeBlock
  ::= /* ... */
  {
    mixin="sample.package.psi.impl.SampleLazyCodeBlock_mixin"
    altConstructorParams=["CharSequence"]
  }
```
now generates:
```
class SampleLazyCodeBlockImpl extends SampleLazyCodeBlock_mixin implements SampleLazyCodeBlock
{
    SampleLazyCodeBlockImpl( ASTNode node )
    {
        super( node );
    }

    SampleLazyCodeBlockImpl( CharSequence arg1 )
    {
        super( arg1 );
    }

    // ...
}
```

**Comment by gregsh** [comment]
Sure, LazyParseablePsiElement is what I forgot about for a moment.

'Forwarding constructors' idea is a natural expected behaviour I guess so.. here it is now.

**Comment by calexHG** [comment]
Naturally I agree. ;)

Of course GK may have specially recognized use cases built into it over time, such as special support for stubs, that it has specific semantic understanding of and thus can make better decisions about (if ever necessary), but I feel that before ever getting to think about that extra-credit stuff, the most important priority GK should have is to just make itself as nonintrusive/invisible as possible, allowing the end-user to do anything that GK hasn't considered yet without it getting in the way.

The first thing that comes to my mind that Java doesn't give for free is that the base constructors get hidden by GK's PSI constructor, and this solves that one.

It's working well. Thanks.
