### ISSUE TITLE
Failed to download JFlex

### ISSUE THREAD

**Issue by igorz-** [JetBrains/Grammar-Kit#106]
Older versions of idea has this error
```
Failed to download 'https://github.com/JetBrains/intellij-community/raw/master/tools/lexer/jflex-1.4/lib/JFlex.jar':
Connection failed with HTTP code 404
```
I think, it's better to use urls, pointing certain commit or tag to be future proof instead of [pointing master branch](https://github.com/JetBrains/Grammar-Kit/blob/master/support/org/intellij/grammar/actions/BnfRunJFlexAction.java#L93)

Example:
```
https://github.com/JetBrains/intellij-community/raw/9bfe6eef127eff25baa4b032e975dc7a7ed32f22/tools/lexer/jflex-1.4/lib/JFlex.jar
```

**Comment by gregsh** [comment]
I agree. See #103 for workaround.

**Comment by igorz-** [comment]
Thanks.
