### ISSUE TITLE
The names that rule-parsing functions get defined as differ from the names used to call them

### ISSUE THREAD

**Issue by calexHG** [JetBrains/Grammar-Kit#107]
There's some leftover code, somewhere still not using the newly unified identifier naming, which is causing troubles.

I've tentatively avoided the problem by solving it indirectly, through fixing another issue.. I've implemented a slice of what I was asking from you back in issue #97 (removing some of the unwanted name mangling GK intrusively performs on the identifiers given to it) and naturally that avoids the problem.

It obviously doesn't truly fix the underlying hole which is sitting somewhere in the generation code, but I'm pasting the bad generated code below, and you'll surely know immediately which code path is involved with my example that didn't get updated..

**Comment by calexHG** [comment]
```
Foo ::= &Foo__predicate Foo__inner {
  recoverWhile=Foo__recovery
}
Foo__predicate ::=
Foo__recovery ::=
Foo__inner ::=
```

generates...

	  /* ********************************************************** */
	  // &Foo__predicate Foo__inner
	  public static boolean Foo(PsiBuilder builder, int level) {
	    if (!recursion_guard_(builder, level, "Foo")) return false;
	    boolean result;
	    Marker marker = enter_section_(builder, level, _NONE_, FOO, "<foo>");
	    result = Foo_0(builder, level + 1);
	    result = result && Foo__inner(builder, level + 1);
	    exit_section_(builder, level, marker, result, false, Foo__recovery_parser_);
	    return result;
	  }

	  // &Foo__predicate
	  private static boolean Foo_0(PsiBuilder builder, int level) {
	    if (!recursion_guard_(builder, level, "Foo_0")) return false;
	    boolean result;
	    Marker marker = enter_section_(builder, level, _AND_);
	    result = Foo__predicate(builder, level + 1);
	    exit_section_(builder, level, marker, result, false, null);
	    return result;
	  }

	  /* ********************************************************** */
	  public static boolean Foo_inner(PsiBuilder builder, int level) {
	    Marker marker = enter_section_(builder);
	    exit_section_(builder, marker, FOO_INNER, true);
	    return true;
	  }

	  /* ********************************************************** */
	  public static boolean Foo_predicate(PsiBuilder builder, int level) {
	    Marker marker = enter_section_(builder);
	    exit_section_(builder, marker, FOO_PREDICATE, true);
	    return true;
	  }

	  /* ********************************************************** */
	  public static boolean Foo_recovery(PsiBuilder builder, int level) {
	    Marker marker = enter_section_(builder);
	    exit_section_(builder, marker, FOO_RECOVERY, true);
	    return true;
	  }

With PR #108 this example gets generated correctly as shown below, although not because actual bug has been found and patched..:

	  /* ********************************************************** */
	  // &Foo__predicate Foo__inner
	  public static boolean Foo(PsiBuilder builder, int level) {
	    if (!recursion_guard_(builder, level, "Foo")) return false;
	    boolean result;
	    Marker marker = enter_section_(builder, level, _NONE_, FOO, "<foo>");
	    result = Foo_0(builder, level + 1);
	    result = result && Foo__inner(builder, level + 1);
	    exit_section_(builder, level, marker, result, false, Foo__recovery_parser_);
	    return result;
	  }

	  // &Foo__predicate
	  private static boolean Foo_0(PsiBuilder builder, int level) {
	    if (!recursion_guard_(builder, level, "Foo_0")) return false;
	    boolean result;
	    Marker marker = enter_section_(builder, level, _AND_);
	    result = Foo__predicate(builder, level + 1);
	    exit_section_(builder, level, marker, result, false, null);
	    return result;
	  }

	  /* ********************************************************** */
	  public static boolean Foo__inner(PsiBuilder builder, int level) {
	    Marker marker = enter_section_(builder);
	    exit_section_(builder, marker, FOO__INNER, true);
	    return true;
	  }

	  /* ********************************************************** */
	  public static boolean Foo__predicate(PsiBuilder builder, int level) {
	    Marker marker = enter_section_(builder);
	    exit_section_(builder, marker, FOO__PREDICATE, true);
	    return true;
	  }

	  /* ********************************************************** */
	  public static boolean Foo__recovery(PsiBuilder builder, int level) {
	    Marker marker = enter_section_(builder);
	    exit_section_(builder, marker, FOO__RECOVERY, true);
	    return true;
	  }


// --

**Comment by gregsh** [comment]
Thanks. The hole no more.

**Comment by calexHG** [comment]
Thanks. Lol, from looking at the tests, I'm still wonder how in the heck someone would ever get GK to parse a rule name with spaces in it ;]

(I guess it supports using quotes around the names or sumthin' :p)

**Comment by gregsh** [comment]
Originally I did angles-quoted syntax because [of this](http://savage.net.au/SQL/sql-92.bnf.html)

**Comment by calexHG** [comment]
Ahhhhh

I see. Yeah.. Well, I guess that is what it comes down to in the end: making the process easier.
