### ISSUE TITLE
Non-generated tokens support (multiple sub-issues)

### ISSUE THREAD

**Issue by calexHG** [JetBrains/Grammar-Kit#110]
_[I've had this sitting, incomplete, in a browser tab, unsubmitted for a while now while dealing with other things.. better to just quickly list what has come up and get it out there, so it can hopefully be addressed.]_

Is it correct that one can only reference tokens in their element-accessor query strings if they have GK's token generation enabled? GK reports an "incorrect item" error when mentioning tokens in that context  and that goes away when enabling it (which somewhat makes sense given the limitation mentioned later).

I don't want GK's token generation[1]. But the problem that exists there is that  — n/m... point is: GK's parsing code works just fine with my separately defined tokens b/c I static import them in the `parserImports`. Why should they cause problems here?

(Just as a reminder in case it becomes relevant, do note that, at the moment, the `parserImports` statements that currently allow the _parser_ to deal with user tokens, do not currently get used when generating _PSI_ class files)

_[1] I originally disabled GK's token generation ages ago because it was mangling my token names (turning, say, GT_GT_EQUAL, into GTGTEQUAL) IIRC (or maybe it was something else), but that seems to be resolved now. In any case, I don't want GK's token generation anymore. I have my own system that uses its own IElementType class hierarchy, specially tweaked debugNames, token aliases, logical visual arrangement into clumps of related tokens, etc._

**Comment by gregsh** [comment]
I'd welcome some short sample to understand the problem.
Token constants generation doesn't directly relate to PSI accessors in my opinion.

**Comment by calexHG** [comment]
> Just checked that I've forgot to mention that in 'methods' attribute documentation.
> 
> The path is /-separated list of items. Item is:
> 
>     the name of a rule or a token
>     name[index], index=number, 'first' or 'last'
> 
> '//' is not supported, but now it can be easily implemented via SyntaxTraverser API

    {
        // ...
        generate=[
            names="long"
            token-case="as-is"
            tokens="no"
            tokenAccessors="no"//"yes"
        ]
    }

    // this example is obviously useless, but my real usage isn't
    NamedFooBar ::= Foo IDENTIFIER Bar {
        methods=[
            myFoo="/Foo"
            myBar="/Bar"
            myId="/IDENTIFIER"
        ]
    }
    Foo ::=
    Bar ::=

..results in:

    5:56:11 PM incorrect item 'IDENTIFIER' in 'NamedFooBar' method myId="/IDENTIFIER"

..generating:

    public class SampleNamedFooBar_Impl extends ASTWrapperPsiElement implements SampleNamedFooBar {

      // ...constructor & visitor methods...
      
      @Override
      @NotNull
      public SampleBar getBar() {
        return findNotNullChildByClass(SampleBar.class);
      }

      @Override
      @NotNull
      public SampleFoo getFoo() {
        return findNotNullChildByClass(SampleFoo.class);
      }

      @Override
      @NotNull
      public SampleFoo getMyFoo() {
        return getFoo();
      }

      @Override
      @NotNull
      public SampleBar getMyBar() {
        return getBar();
      }

      // <-- no getMyId()

    }

**Comment by calexHG** [comment]
Option 2:

Enabling token accessors, the `incorrect item` error isn't generated, and the methods below get added, but the code is invalid because the token type constant is not imported.

	  @Override
	  @NotNull
	  public PsiElement getIdentifier() {
	    return findNotNullChildByType(IDENTIFIER); // <-- Error: Cannot resolve symbol 'IDENTIFIER'
	  }

	  @Override
	  @NotNull
	  public PsiElement getMyId() {
	    return getIdentifier();
	  }

**Comment by calexHG** [comment]
Hack/workaround attempt 1:

	// THIS DOES NOT WORK:
	classHeader="import static sample.package.SampleTokenTypes.*;"

This workaround attempt for the lack of a "parserImports" for PSI classes doesn't work because the header gets placed above the package declaration, which would invalid Java.

**Comment by calexHG** [comment]
And, you're right, adding token generation..

    generate=[
        names="long"
        token-case="as-is"
        tokens="yes"
        tokenAccessors="no"//"yes"
    ]
    tokens=[
        IDENTIFIER="blah"
    ]

Still results in the incorrect item. My bad. It was the `tokenAccessors` that must have effected that. This issue was on the backburner for a few days and without going back fully re-examining exactly what was effecting what, I just wanted to at least get the issue reported.

**Comment by calexHG** [comment]
_[ just updated the original example bnf to explicitly mention the following details, as they help to paint the picture of how things are being used ]_
```
    parserImports=[
        "static sample.package.SampleTokenTypes.*"
        "sample.package.SampleTokenTypes"
    ]
    elementTypeHolderClass="sample.package.GeneratedSampleElementTypes"
```

**Comment by calexHG** [comment]
Ahh... here's where the token generation made a difference:

Trying eliminating the leading slash gets it to accept the token reference and generate the custom-named accessor method, but only when token generation is enabled.

```
{
    generate=[
        names="long"
        token-case="as-is"
        tokens="no"
        tokenAccessors="no"//"yes"
    ]
    tokens=[ IDENTIFIER="blah" ]
}

NamedFooBar ::= Foo IDENTIFIER Bar {
    methods=[
        myFoo="/Foo"
        myBar="/Bar"
        myId="IDENTIFIER"
    ]
}
Foo ::=
Bar ::=
```
..somehow finally manages to produce the custom-specified accessor without tokenAccessors being toggled on, like it should be able to:

```
  @Override
  @NotNull
  public PsiElement getMyId() {
    return findNotNullChildByType(IDENTIFIER);
  }
```

but, naturally, the symbol is undefined because there is apparently no way to get it imported, and this non-absolute, no-leading-forward-slash syntax workaround likely doesn't work for more complex queries.

There ya go -- ya managed to get almost the whole, original, long-winded explanation out of me! :p

**Comment by gregsh** [comment]
Without "/" it thinks one wants to _rename_ the getter.
With generate=[tokens="yes"] and "/" it reuses existing getter to generate a new accessor.
That's OK.

What's not is the missing constant.
Now "static * "  parser imports are also added to a PSI impl class with token accessors.

**Comment by calexHG** [comment]
Part of the problem is... I interpret the special "methods" syntax feature as: "this allows you to use concise syntax instructing GK to create accessors for some arbitrary item within the element tree". I interpret generate.tokenAccessors as: "without needing to custom specify an accessor using the methods syntax, have GK automatically create one by default, for any child-level tokens". I don't expect either one to rely on the other.

**Comment by gregsh** [comment]
"methods" attribute grew out of "methodRenames" attribute which purpose was to resolve naming conflicts like "getClass()" as well as suppressing some accessors.

I understand that having specified ```myId="IDENTIFIER"``` and not seeing it is rather confusing.
Certain amends can be made to address that. Will that suffice?

**Comment by gregsh** [comment]
@calexHG 
I wonder if you'd be interested in improving Grammar-Kit documentation for future generations.
You seem to like writing texts as much as I hate it ;-)
