### ISSUE TITLE
Invalid accessor is generated when using elementType

### ISSUE THREAD

**Issue by matklad** [JetBrains/Grammar-Kit#111]
Consider the following grammar:

```
root ::= thing
thing ::= <<id bar>>

foo ::= "foo"
bar ::= "bar" {elementType=foo}

private meta id ::= <<param>>
```

Grammar Kit generates `Foo` PSI class and does not generate `Bar` PSI class, which is correct. However, the `Thing` gets the following accessor:

```Java
@NotNull
Bar getBar();
```

which fails to compile because there is no `Bar`

Interestingly, if I add parenthesis like `thing ::= <<id (bar)>>`, then the correct accessor is generated:

```Java
@NotNull
RustFoo getFoo();
```

I am using the latest published 1.3.1 pre release.

**Comment by matklad** [comment]
Hm, actually the meta rule is irrelevant:

```
// fails to compile
root ::= thing
thing ::= bar

foo ::= "foo"
bar ::= "bar" {elementType=foo}
```

```
// compiles
root ::= thing
thing ::= (bar)

foo ::= "foo"
bar ::= "bar" {elementType=foo}
```

**Comment by gregsh** [comment]
Thanks, fixed
