### ISSUE TITLE
Wrong JFlex URL

### ISSUE THREAD

**Issue by durkiewicz** [JetBrains/Grammar-Kit#112]
When I try to generate a lexer from a .flex file for the first time, I get a popup for downloading JFlex files. Unfortunately, it has a link to previous JFlex version and I get an error like that:

![screenshot from 2016-05-21 04 54 53](https://cloud.githubusercontent.com/assets/2900637/15446029/9e731c64-1f11-11e6-9bc9-64a66959bba3.png)

**Comment by MarcusDalgren** [comment]
I get this error too in the latest version of Intellij IDEA (2016.1.2).
Being the tenacious idiot I am I routed github.com through my local computer.
The files now get downloaded ok but I get the following error: Error: unknown option "-sliceandcharat".
The full command being run looks like this:
"C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.1.2\jre\jre\bin\java" -Xmx512m -Dfile.encoding=windows-1252 -classpath C:\IdeaProjects\idea-silverstripe\JFlex.jar JFlex.Main -sliceandcharat -skel C:\IdeaProjects\idea-silverstripe\idea-flex.skeleton -d C:\IdeaProjects\idea-silverstripe\src\com\raket\silverstripe C:\IdeaProjects\idea-silverstripe\src\com\raket\silverstripe\SilverStripe.flex

**Comment by gregsh** [comment]
Please use [JFlex.jar from 145 branch](https://github.com/JetBrains/intellij-community/blob/145/tools/lexer/jflex-1.4/lib/JFlex.jar)

**Comment by MarcusDalgren** [comment]
Wow thanks for the quick reply!
It works with 1.3.0 for me now and I'll try out the pre release of 1.3.1.
Thank you!

**Comment by gregsh** [comment]
GK 1.4.0 is published on plugins.jetbrains.com. Closing.
