### ISSUE TITLE
Hooks don't always get called for private rules

### ISSUE THREAD

**Issue by matklad** [JetBrains/Grammar-Kit#113]
Are hooks supported for private rules? Consider this grammar:

```
root ::= thing
thing ::= bar
foo ::= "foo"
private bar ::= foo foo { hooks = [myHook] }
```

Grammar Kit generates the following parsing code for `bar`:

```Java
  /* ********************************************************** */
  // foo foo
  static boolean bar(PsiBuilder builder_, int level_) {
    if (!recursion_guard_(builder_, level_, "bar")) return false;
    boolean result_;
    Marker marker_ = enter_section_(builder_);
    result_ = foo(builder_, level_ + 1);
    result_ = result_ && foo(builder_, level_ + 1);
    register_hook_(builder_, level_, MY_HOOK, null);
    exit_section_(builder_, marker_, null, result_);
    return result_;
  }
```

Note that the hook is installed, but it is never executed because [this version] of `exit_section_` does not execute hooks.

I can work around this if I change the rule to

```
private bar ::= foo foo () { hooks = [myHook] pin = 2}
```

It forces Grammar Kit to use [another version] of `exit_section_` which fires hooks. 

[this version]: https://github.com/JetBrains/Grammar-Kit/blob/316d19c772ceea27148ea17b959b686b65e7553d/support/org/intellij/grammar/parser/GeneratedParserUtilBase.java#L450

[another version]: https://github.com/JetBrains/Grammar-Kit/blob/316d19c772ceea27148ea17b959b686b65e7553d/support/org/intellij/grammar/parser/GeneratedParserUtilBase.java#L500

**Comment by gregsh** [comment]
"level" tracking needs to be moved to ErrorState, as there's no level arg in the simpler exit_section.
What do you want to achieve with a hook on a private rule?

**Comment by matklad** [comment]
>What do you want to achieve with a hook on a private rule?

A good question! I want to simulate "contexts" with the help of a private rule. Let me explain by an example. 

# Intro

In Rust, if expressions looks like this `if true {1} else {2}` and a struct expression looks like this `S {f: true}`. And there is a rule that says that struct literals are forbidden in `if` expressions, because things like `if S {f: true}.f {1} else {2}` are difficult to parse. `if (S {f: true}.f) {1} else {2}` is allowed though. 

In the original hand written parser this is handled by maintaining an `are_struct_literals_allowed` context field on the parser. When we enter `if` expression it is set to false, and upon entering parenthesized expression it is set to true.

In grammar kit, this can be handled by duplicating expression grammar (all of its rules recursively), but this is unfortunate. So we simulate this contexts in our parser. This approach:

```
private expr_with_structs ::=  <<pushAllowStructLiterals>> expr <<popAllowStructLiterals>>
```

does not work: if parsing inner `expr` returns false then the context is not popped. So we have to use [something like this]

```
private expr_with_structs ::= <<withStructLiteralsAllowed expr>> 
```

But it does not work either, because GrammarKit fails to generate `getExpr` accessor for `parenthesises_expr` (`'(' expr_with_structs ')'`). So we use `!()` [workaround], but it isn't pretty and may produce wrong `@Nullability` annotations. 

# Using hooks for contexts 

So, because hooks are like `finally` handlers it makes sense to try something like

```
expr_with_structs ::= <<enterContext STRUCT_LITERAL_ALLOWED true>> expr  {
  hooks=[popContext]
}
```

And it actually works if I employ the workaround. 

# Provide a general context mechanism 

Looks like this "context sensitivity" is a common use case: there is another set of rules for Rust where it is used. It also used in the [Go plugin] together with `!()` hack and in the [Dart plugin]. Perhaps it makes sense to build it into the parser? Or am I just missing some good way to implement it with the current Grammar Kit?

[workaround]: https://github.com/intellij-rust/intellij-rust/blob/13be15ae32b90acc6950f87a9c58dce631a3196f/src/main/kotlin/org/rust/lang/core/grammar/rust.bnf#L830

[something like this]: https://github.com/intellij-rust/intellij-rust/blob/13be15ae32b90acc6950f87a9c58dce631a3196f/src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt#L67

[Go plugin]: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/c8689d26e86c5479eb84b17d248281ec7c00435f/grammars/go.bnf#L191

[Dart plugin]: https://github.com/JetBrains/intellij-plugins/blob/a37e133b767d5b407b172758bce8475515becc16/Dart/src/com/jetbrains/lang/dart/DartGeneratedParserUtilBase.java#L30

**Comment by matklad** [comment]
And may I ask a question why we are at it? What are exception safety grantees of the generated parser? Should we use try/finally, [like we do at the moment](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt#L109-L114), or is

```
val old = getUserData(key)
putUserData(key, value)
val result = block()
putUserData(key, old)
return result
```

sufficient?

**Comment by gregsh** [comment]
2. Exception handling is not required for a parser. PsiBuilder may throw ProcessCancelledException so that full reparse is re-scheduled. And it is also a bit faster without try/finally blocks.

1. We do contexts via "pin" feature as far as all sub-expressions are tried in a pinned rule.
````private expr_with_structs ::=  <<pushAllowStructLiterals>> expr <<popAllowStructLiterals>> { pin=1 }``` The pin here ensures that <<pop>> is called whenever <<push>> is good. 


0. The hooks on private rules and public rules with simplified sections: still thinking on this matter.

**Comment by matklad** [comment]
>We do contexts via "pin" feature as far as all sub-expressions are tried in a pinned rule.

I see. However, it is still not a perfect solution. If you have an optional `expr_with_structs?` anywhere, you need to use something along the lines of

```
private expr_with_structs ::= &expr_start <<pushAllowStructLiterals>> expr <<popAllowStructLiterals>>
{ pin=1 }

private expr_start ::= a | whole | bunch | of | stuff | ...
```

and you still loose not null annotations because of the pin.

**Comment by gregsh** [comment]
Mixing BNF and hooks to achieve push/pop behavior seems a bit off style to me. Here's the way to overcome the nullability problem:
````
expr_with_structs ::= &expr_start <<pushAllowStructLiterals>> expr <<popAllowStructLiterals>>
{ pin=1 extends=expr}
````

**Comment by matklad** [comment]
Yep, this is the trick [we use at the moment](https://github.com/intellij-rust/intellij-rust/blob/e41b217f7b62f3fd1256ed47affd4c5be229435b/src/main/kotlin/org/rust/lang/core/grammar/rust.bnf#L770-L773). Actually, any solution here works OK, it was just that I was experimenting with yet another one and hit

**Comment by gregsh** [comment]
I've updated the 1.3.1 pre-release binaries. Check it out.
