### ISSUE TITLE
Support for grammars with preprocessors and sometimes optional semicolons

### ISSUE THREAD

**Issue by collinsmith** [JetBrains/Grammar-Kit#118]
I'm trying to add support for a language which has sometimes optional semicolons, and required at others, depending on a preprocessor pragma directive. I was wondering if this was even possible with the grammar kit. I think the cleanest implementation would be to do a pass before the lexer is applied to analyze the preprocessor directives and set the state, but I cannot find any documentation on how to set these states within the BNF file. As semicolons are sometimes optional, my grammar needs to consider EOL as a parseable token, however EOL and LINE_WS are automatically generated tokens in the resulting flex file, which results in a conflict with my grammar (namely my tokens are unreachable unless I remove the auto-generated ones from the flex file's declarations).

I have been reading over the TUTORIAL and HOWTO sections, but they seem to really skim over a lot of the features that might be useful regarding this, namely external rules. I've written a sample external rule to test with (off of the initial state so it should be guaranteed to run), but it doesn't seem to be executing, as it contains a RuntimeException that doesn't ever seem to be thrown (I tried printing to stdout too, but throwing a RuntimeException should at least tell me it's executing).

Here are some examples from the language. I've added in [EOL] where it's expected
`#include "string"[EOL]`
`#pragma deprecated This is the message to display as the deprecated string[EOL]`
`#pragma semicolon 1`
`int i = 0[EOL or SEMICOLON depending on pragma state]`

I saw within one of your patch notes (1.1.5) support was added for "empty tokens support (lexer-based preprocessors)", however I cannot find any clear documentation or examples on how to use this feature. Is there any documentation on a method I can use to manually read a portion of the file to generate my own tokens? If there is not, can I request that some be written? I was looking at one of the [html doc files](https://github.com/JetBrains/Grammar-Kit/blob/master/support/messages/attributeDescriptions/parserUtilClass.html), but it doesn't give any context to the param it provides.

I'd also like to apologize if this is not the appropriate place to inquire about this stuff, but I could not find any forum, and the IntelliJ page links back to Github. A lot of the problems I've been running into seem to be corner cases, and I'm starting to think that it might be best to write at least the flex file manually.

**Comment by gregsh** [comment]
Please direct this question to the community and search for some insights here:
https://intellij-support.jetbrains.com/hc/en-us/community/topics/200366979-IntelliJ-IDEA-Open-API-and-Plugin-Development
Short answer: yes, it is surely possible.

**Comment by collinsmith** [comment]
Sure thing. Thank you for the info!
