### ISSUE TITLE
Invalid parser generated using a token as a parameter

### ISSUE THREAD

**Issue by collinsmith** [JetBrains/Grammar-Kit#119]
I came across an issue when trying to pass a token as a parameter into an external rule. After the parser is generated, the resulting proxy contains a `Cannot resolve symbol 'character_string'` error. Is this an expected behavior? The following is a snippet bnf which should reproduce the behavior:

```
{
  parserUtilClass="net.alliedmods.intellij.sourcepawn.parser.SourcePawnParserUtils"

  tokens=[
    character_string="regexp:'.+'"
  ]
}

root ::= root_item *
private root_item ::= !<<eof>> character_literal ';'
external character_literal ::= parsePawnCharacterLiteral character_string
```

I was able to workaround this behavior by creating a proxy rule:
```
external character_literal ::= parsePawnCharacterLiteral temp
temp ::= character_string
```

**Comment by gregsh** [comment]
That's a bug, thanks. A simpler workaround is:
````external character_literal ::= parsePawnCharacterLiteral (character_string)````
