### ISSUE TITLE
1.4.0 uses methods not available in current IDEA

### ISSUE THREAD

**Issue by eprst** [JetBrains/Grammar-Kit#120]
1.4.0 uses newly added `PsiTreeUtil.getStubChildOfType/getStubChildrenOfType` which are not yet available in the latest IDEA version. As a result, generated code doesn't compile.

I guess you want to change `since-build` so that grammar-kit doesn't get updated to 1.4.0 until corresponding IDEA version is released.

**Comment by gregsh** [comment]
Methods are backported to appropriate branches. They are already available in 2016.1.3 EAP.
For the time being one can use ````psiTreeUtilClass```` attribute to provide one's own PsiTreeUtil.

No one wants to go back, it is dark and buggy there, so no since-builds! :-)
