### ISSUE TITLE
maunual newline/whitespace handling?

### ISSUE THREAD

**Issue by Achati** [JetBrains/Grammar-Kit#124]
in the grammar i am trying to write in bnf a tag can be continued on a newline with '\'
but with a newline without backslash it would start a new tag

so far using bnf, the live preview and the PsiViewer it sems like i cannot see newlines or other spaces as tags

how would i make sure to see at least newlines and make them useable tokens ?

at the moment it behaves like so: 

```
"literal tag 1"
"literal tag 2"
"literal tag 3"
```
is behing turned into
```
TAG
    LITERAL
    LITERAL
    LITERAL
``` 
this is valid, if it were all in one line, but not if its on a newline

what it should do (but cant until i figure out how to use newlines):
```
TAG
    LITERAL
NEWLINE
TAG
    LITERAL
NEWLINE
TAG
    LITERAL
```

**Comment by gregsh** [comment]
Regexp tokens that matches space or \n are added to whitespace TokenSet by LivePreview (and thus skipped by PsiBuilder) if they are not used anywhere in grammar. Check the following grammar in LivePreview:

````
{
  tokens = [
    newline = "regexp:\n"
    word = "regexp:\w+"
    space = "regexp:\s+"
  ]
}

root ::= (line line_break)*
line_break ::= newline * 
line ::= word (space word) * 
````

In production I would move that logic to the lexer.

**Comment by Achati** [comment]
well using your advice i managed to get it to work in the live preview,
but when i load up the intellij plugin its not working in the "production" environment

how do i even move that logic into the lexer? do i have to edit the .flex file every time ido changes to the .bnf ? or do i have to mess with the generated java code ?

**Comment by gregsh** [comment]
My proposed workflow is:
1. prototype the grammar in LivePreview
2. generate *.flex stub to sources and generate inital lexer version from it
3. create ParserDefinition and/or setup lexer and parser tests
3. perfect the *.flex & *.bnf separately

Flex file shall be edited manually as it is likely to contain complex logic that is absent in *.bnf.

**Comment by Achati** [comment]
i managed to do everything except one last thing

how do i name the newline/whitspace tokens so that they are recognized as PsiWhitespace by the live preview Psi Viewer ?

apart from that everything works and it was just a matter of uncommenting EOL in the .flex
thank you very much

**Comment by gregsh** [comment]
LivePreviewLexer treats a *regexp* token as *WHITE_SPACE* if its pattern matches ' ' or '\n' and the token is never used in BNF rules. This mimics PsiBuilder behaviour as it never feeds a parser with whitespaces and comments.

**Comment by Achati** [comment]
i guess i cannot use it then since i need to handle at least newlines manually.. maybe even spaces later, but i'd try to avoid that

**Comment by gregsh** [comment]
When you switch to production *.flex lexer you don't really need *LivePreview*.
I've updated "My proposed workflow" comment above to state it explictly.

**Comment by Achati** [comment]
yeah i am using the live preview less and less
but now i run into issues in implementing features because i defined some literals with their enclosing types in regex.. not sure how to do otherwise.. but i have not tried all things yet, i will l
come back if i fail to figure it out

another partially relevant question for me.. how do i make sure that there may never be spaces between two tokens ?
i tried `token1 !'"regexp:\s+" token2`
and using the ParserDefinition.spaceExistanceTypeBetweenTokens method
both seem to have no effect or i misunderstand what they are supposed to do

**Comment by gregsh** [comment]
There's no such thing as space between tokens.
Lexer splits text into stream of tokens, space as any other chars may or may not be a separate token or a part of one.

ParserDefinition#spaceExistanceTypeBetweenTokens is only used in code generation.
During IDEA plugin development one shall always dig the usages of any platform methods
in the platform source code.

> i tried token1 !"regexp:\s+" token2
and using the ParserDefinition.spaceExistanceTypeBetweenTokens method
