### ISSUE TITLE
Inconsistent capitalization of EOL in generated class names vs files

### ISSUE THREAD

**Issue by KronicDeth** [JetBrains/Grammar-Kit#126]
I have a rule, `escapedEOL`, that when generated in Grammar Kit v1.4.1, has files named `ElixirEscapedEOLImpl.java`, which was the name for the previous version of Grammar KIt, but the class itself has  `Eol`, so `ElixirEscapedEolImpl`.  The same happens for the interface: the file uses `EOL` while the interface is `Eol`.

You can see the inconsistent naming in [this tag](https://github.com/KronicDeth/intellij-elixir/releases/tag/grammar-kit-1.4.1-before-manual-fixes)

**Comment by KronicDeth** [comment]
The inconsistent naming also seems to drop a method that should be attached:

![screen shot 2016-07-16 at 3 15 53 pm](https://cloud.githubusercontent.com/assets/298259/16896928/3849cce8-4b68-11e6-8bb5-cd27bfae8525.png)

**Comment by KronicDeth** [comment]
[This](https://github.com/KronicDeth/intellij-elixir/releases/tag/grammar-kit-1.4.1-after-manual-fixes) is the tag with my manual fixes to get the generated code to compile.

**Comment by gregsh** [comment]
The observed behaviour where file and class-name casing do not match is caused by a case-insensitive file-system. Instead of a new "Eol" file it reused the existing "EOL". 

I've pushed the small fix so that "EOL" case is preserved.

**Comment by gregsh** [comment]
Grab the latest build from [[teamcity.jetbrains.com]](https://teamcity.jetbrains.com/guestAuth/repository/download/IntellijIdeaPlugins_GrammarKit_Build/.lastSuccessful/GrammarKit.zip-1.4.1.SNAPSHOT.zip)
