### ISSUE TITLE
Poor parser recovery for the first element of the list

### ISSUE THREAD

**Issue by matklad** [JetBrains/Grammar-Kit#128]
Consider the following grammar:

```
root ::= thing*

thing ::= '{' a* '}' {pin=1}
a ::= "A" {pin=1 recoverWhile=a_recover}
a_recover ::= !("A" | '}')
```

For inputs 

```
{       }
{ A     }
{ A B   }
{ A B A }
{ B     }
{ B B   }
```

It recovers properly and matches `{` with `}` (that is, `thing` node encompasses everything between the braces). 

However it fails to recover for the following input:

```
{ B A   }
```

Here `thing` spans only over `{` and `B`. `A` with `}` are just floating in the air. 

I would expect that the last case should also work. Am I using `recover_while` attribute incorrectly?

GK version 1.4.2

**Comment by jvolkman** [comment]
I think you need another layer of block elements. Currently, if you don't first match an "A" at the beginning of your thing block, the parser does not know what to do. `a_recovery` does not apply in that case because an `a` rule was never matched.

The culprit is the code the code generated for a rule like `a*`:
```
  // a*
  private static boolean thing_1(PsiBuilder b, int l) {
    if (!recursion_guard_(b, l, "thing_1")) return false;
    int c = current_position_(b);
    while (true) {
      if (!a(b, l + 1)) break;
      if (!empty_element_parsed_guard_(b, "thing_1", c)) break;
      c = current_position_(b);
    }
    return true;
  }
```
If the `a` rule doesn't match (e.g., "B A"), the while loop ends and no more `a` elements are parsed.

Try adding another layer which matches anything that should be considered a block element, even if it's invalid. Since your block ends with '}', a block entry is anything that isn't '}'.

```
root ::= thing*
thing ::= '{' thing_entry* '}' {pin=1}
thing_entry ::= !'}' a {pin=1} // this pin is important
a ::= "A" {pin=1 recoverWhile=a_recover}
a_recover ::= !("A" | '}')
```

In my grammar, I've generalized this with some meta rules:

```
root ::= << Block entry >>*

entry ::= ...
private meta Block ::= '{' <<BlockEntry <<p>>>>* '}' { pin = 1 }
private meta BlockEntry ::= !'}' <<p>> { pin = 1 }
```

**Comment by matklad** [comment]
Thanks! This is indeed how it works.

**Comment by dnltsk** [comment]
Unfortunately I cannot reproduce your suggested solution. The Live Preview lists errors as shown in the screenshot
<img width="655" alt="bnf-recover" src="https://cloud.githubusercontent.com/assets/8955617/25290882/1b3d8e20-26d0-11e7-91ef-657b3c947614.png">

Did I missed something fundamentally here or is the Live Preview the wrong place to check the that way Grammar?

In my particular case/language a block starts with a keyword and ends with the "end"-keyword. So I tried the following:
```
RootObject ::= ROOT RootObject_entry* END {pin=1 recoverWhile=RootObject_recover}
private RootObject_entry ::= !END ( NameAttr | TitleAttr )
private RootObject_recover ::= !( NAME | TITLE | END )
private NameAttr ::= NAME string {pin=1}
private TitleAttr ::= TITLE string {pin=1}
```
see https://github.com/dnltsk/intellij-mapfile-plugin/blob/master/src/org/dnltsk/mapfileplugin/Mapfile.bnf#L52

Thanks for any hints!

**Comment by dnltsk** [comment]
Found the problem
1. The suggestion above works fine with the header, listed in TUTORIAL.md
2. recoverWhile in my particular case/language works fine with the following bnf:
```
root ::= RootObject*
RootObject ::= ROOT RootObject_entry* END {pin=1}
RootObject_entry ::= !END ( TitleAttr | NameAttr ) {pin=1} // this pin is important

private NameAttr ::= NAME string {pin=1 recoverWhile=title_recover}
private name_recover ::= !( END | NAME )

private TitleAttr ::= TITLE string {pin=1 recoverWhile=name_recover}
private title_recover ::= !( END | TITLE )
```

Thanks and best regards!
