### ISSUE TITLE
"The system is out of resources." java.lang.StackOverflowError from generated BNF code.

### ISSUE THREAD

**Issue by rekendahl** [JetBrains/Grammar-Kit#138]
Hi,

I'm working on a SystemVerilog plug-in. I'm using Gradle, Kotlin and a grammar kit BNF/Flex file. 

During compile I get a "The system is out of resources"  java.lang.StackOverflowError while compiling the generated elementTypeHolderClass called SystemVerilogCompositeElementTypes.java

SystemVerilog is a LARGE language and the official BNF (that I have translated) complex so the generated file is long (~4000 lines). A couple of days ago the compile worked and the resulting plug-in basically worked (it's early days). Since then I get this error consistently (after fixing some mistakes in the BNF). I have tried to increate resources to the Java VM but I have not been successful. 

I need some help figuring out what causes this failure and what I can do!

Here is a short summary of the error and you can click this link for complete log:
[edaphic_coder_out_of_resources.txt](https://github.com/JetBrains/Grammar-Kit/files/512269/edaphic_coder_out_of_resources.txt)

```
[parsing started RegularFileObject[/Users/ekendahl/Projects/edaphic/coder/gen/tech/edaphic/coder/systemverilog/psi/SystemVerilogCompositeElementTypes.java]]


The system is out of resources.
Consult the following stack trace for details.
java.lang.StackOverflowError
	at com.sun.tools.javac.parser.JavacParser.nextToken(JavacParser.java:301)
	at com.sun.tools.javac.parser.JavacParser.arguments(JavacParser.java:1777)
	at com.sun.tools.javac.parser.JavacParser.classCreatorRest(JavacParser.java:2219)
	at com.sun.tools.javac.parser.JavacParser.creator(JavacParser.java:2103)
	at com.sun.tools.javac.parser.JavacParser.term3(JavacParser.java:1166)
	at com.sun.tools.javac.parser.JavacParser.term2(JavacParser.java:909)
	at com.sun.tools.javac.parser.JavacParser.term1(JavacParser.java:880)
	at com.sun.tools.javac.parser.JavacParser.term(JavacParser.java:836)
	at com.sun.tools.javac.parser.JavacParser.term(JavacParser.java:816)
	at com.sun.tools.javac.parser.JavacParser.parseExpression(JavacParser.java:779)
	at com.sun.tools.javac.parser.JavacParser.parseStatement(JavacParser.java:2537)
	at com.sun.tools.javac.parser.JavacParser.blockStatement(JavacParser.java:2352)
	at com.sun.tools.javac.parser.JavacParser.blockStatements(JavacParser.java:2298)
```

There is no reference to none JacacParser calls in the complete trace so I'm not sure what in the file overloads it.

Help would be much appreciated!

**Comment by jvolkman** [comment]
Have you tried increasing javac's stack size with -J-Xss=<some value>? E.g., -J-Xss=4m

**Comment by rekendahl** [comment]
Not 100% sure how to add that switch.

I appreciate the answer. I've seen that switch suggested and it seems the correct one but I can't seem to set the switch correctly:

I tried adding it under `Settings | Build, Execution, Deployment | Compiler` then `Shared Build Process VM Options` and that changed nothing.

I then tried changing `Settings | Build, Execution, Deployment | Compiler` then `Gradle` and `Gradle VM options` and get a "fatal exception" on launch

Finally I tried adding this to the `build.gradle` file: `tasks.withType(JavaCompile) { options.compilerArgs = ['-J-Xss=4m'] }` and got `invalid flag: -J-Xss=4m`

Do you know where I should be setting it?

**Comment by rekendahl** [comment]
Still haven't been able to figure out how to add the `-J-Xss=4m` correctly into environment.

Also the compiler dies "really fast" when hitting the offending file but looking at the file I don't see anything suspicious. I think there is something more fundamentally wrong with my environment but I can't figure out what....

**Comment by gregsh** [comment]
@rekendahl it should be in Settings | Build | Java Compiler | Additional command line parameters
https://www.jetbrains.com/help/idea/2016.2/java-compiler.html

**Comment by rekendahl** [comment]
@gregsh Thank you for your comment. I got side tracked and then went on vacation but I'm back now. Is there a rule for what should be public vs private? ATM I basically have no private statements.

**Comment by rekendahl** [comment]
@gregsh: Your tip about private rules were correct. I semi-randomly (not sure what the rules for private are) turned a lot of rules private and it made the compile work. Not only that even the preview window seem faster (could be placebo and upgrades). 

I will continue to privatize my BNF file. Are there some documentation and/or hints for what should be private and not? I've looked at other projects and can make educated guesses but I'm not 100% sure what should be public!

Closing this thread.

**Comment by gregsh** [comment]
There's no node for a private rule in AST (abstract syntax tree).
See [rule modifiers](https://github.com/JetBrains/Grammar-Kit#rule-modifiers) overview.

**Comment by apedrero** [comment]
![image](https://user-images.githubusercontent.com/32459741/188181821-54851465-8a34-46c4-9117-173cea7e202e.png)

**Comment by apedrero** [comment]
![image](https://user-images.githubusercontent.com/32459741/188182243-4e163836-b324-4af4-b682-9b091837fb43.png)
