### ISSUE TITLE
How to define precompiler rules?

### ISSUE THREAD

**Issue by rekendahl** [JetBrains/Grammar-Kit#142]
Hi,

I'm working in a large BNF file with many deep recursive rules. It's adapted from an official language spec. The language has a precompiler syntax (i.e. like CPP's #ifndef, #define etc.). These precompiler lines can be inserted on any line (i.e inside any current rule). 

What's the best way to define these rules? I.e I would like something like a global rule saying that any line starting with #ifndef is ok inside any other rule!).

Currently, I'm cheating, by having the precompiler rules matched with a regexp. But that means I then would need to implement all the logic in Kotlin/Java. There must be a better way!

/Robert

**Comment by jvolkman** [comment]
These sound similar to comments, so it seems like they'd be better handled by the lexer rule that the PsiBuilder is aware of. In fact, a quick solution to allow them to exist would be to simply register their token type as a comment token. You might also look at MasqueradingPsiBuilderAdapter which seems like it might do what you want.

**Comment by rekendahl** [comment]
Thank @jvolkman.

I'm handling them as comments right now which makes them regular expressions and thus have less error checking capabilities. Especially for #define like macros it seems like more of a rule description would be appropriate. 

I will take a look at MasqueradingPsiBuilderAdapter and see if that works better!

I appreciate the ideas

**Comment by rekendahl** [comment]
Can't find any info on: `MasqueradingPsiBuilderAdapter`. Do you have any links with example usage?

**Comment by rekendahl** [comment]
So the only solution I see at the moment is using a regular expression rule in the BNF file that ends with `_COMMENT`. Something like `TICK_IFDEF_COMMENT="#ifdef".*`. This makes the BNF be aware of the rule and treat it like a comment. This works ok for ifdef type rules. 

For `#define` that allows for macro definitions this works less well as it looses some of the nice grammar checking for this construct. 

Is there another way to "register a token type as a comment token" that I'm not aware of? One that would allow me to still use the BNF defintion?

**Comment by hurricup** [comment]
If you are writing for IDEA, you should return all tokens that should be treated as comments by com.intellij.lang.ParserDefinition#getCommentTokens

I have a bit similar situation in Perl, where i have here-docs, which can be on any line and annotations, which a comments from the perl side, but not IDE. So i'm lexing them as specific tokens in my flex lexer and returning these tokens from my ParserDefinition. You may reparse them later in your PSI tree using LazyParsableElement

**Comment by rekendahl** [comment]
Ok. Seems like I'm on the right track then. I'll finish up basic parsing for them now (treating them as comments) and might return to look at LazeParsableElement later.

**Comment by hurricup** [comment]
Asking on JetBrains plugin developers forums may be helpful.

**Comment by ignatov** [comment]
Please see an experimental and a bit outdated **macros-support** branch https://github.com/ignatov/intellij-erlang/tree/macros-support

**Comment by rekendahl** [comment]
Thank you.  Will do. 

		_____________________________
