### ISSUE TITLE
ABNF support

### ISSUE THREAD

**Issue by waitingmyself** [JetBrains/Grammar-Kit#144]
do you have a plan to add ABNF support?
thanks~

**Comment by gregsh** [comment]
Looks like it's not hard to convert a single ABNF grammar manually (via regexp-replace).
So I do not see much sense in supporting it currently. What do you need ABNF for?

**Comment by waitingmyself** [comment]
i just want to find a plugin editor for ABNF  Syntax highlighting;
maybe i can try to find other editor~
thanks for your reply~~
