### ISSUE TITLE
How to express complex 'ends with' rule?

### ISSUE THREAD

**Issue by rekendahl** [JetBrains/Grammar-Kit#147]
In my language the following `foreach` syntaxes are all valid:

```
foreach(foo[x]) foo[i] = i;
foreach(foo[x].foo_[i]) ...;
foreach(foo.foo_[i]) ...;
foreach(foo[x][i])...;
```

The overall rule is that `foreach` needs to end with `'[' identifier ']'` (in practice that creates the loop variable to be used in the statement).  The problem is that the hierarchical identifier that comes before can also have several brackets (see written rules below).

The written BNF spec looks (something) like this:

```
foreach_rule ::= 'foreach' '(' array_identifier '[' identifier ']' ')' 
array_identifier ::=  identifier { '[' (identifer | expression) ']' }* 
                      {'.' identifier { '[' (identifier | expression) ']' }* }*
```

To make the rules work I need to guarantee that the rule **ends with** `'[' identifier ']'` but I might or might not have several similar combinations before.

I can't seem to express this in the BNF correctly. Any ideas if this can be done (or do I need to write an external rule for it?)

I see no way to express this with a left-to-right interpreter correctly. I've tried adding {rightAssociative=true} but that doesn't seem to change anything (in the preview). I also, naivley, tried making making the last rule _required_ by changing it to `&('[' identifier ']')` but that didn't seem to do what I wanted (at all).

Is there some clever way to express this that I'm missing?

**Comment by jvolkman** [comment]
As I understand it, the problem is that array_identifier is consuming the last '[' identifier ']' before foreach_rule has a chance. Is that correct?

If so, you could do something like this:

```
identifier ::= IDENTIFIER_LITERAL
expression ::= identifier  // not sure what this is.

private index ::= '[' (identifier | expression) ']'
array_identifier ::= identifier index*
                      {'.' identifier index* }*

private foreach_index ::= !(index ')') index
foreach_array_identifier ::= identifier foreach_index*
                      {'.' identifier foreach_index* }* { elementType = array_identifier }

foreach_rule ::= 'foreach' '(' foreach_array_identifier index ')'
```

I've done two things here:
- Extracted `'[' identifier ']'` into a private rule `index`
- Made foreach variants of both `array_identifier` and `index`

`foreach_array_identifier`'s elementType is `array_identifier`, so it won't generate a new PSI element. However, it differs from `array_identifier` in that it won't parse the last `index` if its followed by a closing paren.

**Comment by rekendahl** [comment]
Interesting! The `!')'` is a clever take on it (the reverse of the "required" that I tried. I think that it could work. I didn't think of that as a possibility. I will look at your code a little closer and try it out in my area and report back.

I appreciate the suggestions!

**Comment by rekendahl** [comment]
Cool. The `!')'` works. Thank you so much. I now have a new tool in my arsenal!
