### ISSUE TITLE
allow JFlex Lexer debugging

### ISSUE THREAD

**Issue by azrdev** [JetBrains/Grammar-Kit#149]
Following the [Custom Language Support Tutorial](http://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support_tutorial.html), I write a grammar-kit parser and a JFlex lexer. I'd like to debug/test the latter on its own, i.e. check the tokens that it generates before the parser applies its grammar. However, JFlex' `%debug` only prints `null` i.e. the EOF token[1], and `%standalone` doesn't even produce a valid Lexer.java file. Seems like these options have been broken in grammar-kits' fork of JFlex.

IDEA 2016.3, Grammar-Kit 1.5.0

[1] the `%debug` lexer only works after inserting this additional code:
~~~
%{
  private static String zzToPrintable(CharSequence cs) {
    return zzToPrintable(cs.toString());
  }
%}
~~~

**Comment by gregsh** [comment]
%debug option: use jflex jar from the commit above.

%standalone option: it is not expected to work this way at all.
See "Why do standalone scanners have a different standard return type" at http://jflex.de/faq.html

**Comment by azrdev** [comment]
@gregsh I copied the jflex*.jar to my projects' root directory, replacing the existing file of the same name. Regenerating the .flex file yields a different lexer as expected, but running that file as Application still only prints `null` once.

**Comment by gregsh** [comment]
I used %debug option yesterday and it worked as expected.

1. "Generate Lexer" output in Run tool window shows generator command line. Make sure the flex.jar in  output is the right one.
2. If the problem persist I'd debug the output calls

**Comment by azrdev** [comment]
@gregsh still no improvement here:
1. it is using [the jflex.jar](https://github.com/JetBrains/intellij-community/blob/b7f882a7a99554e7e3b9cdbf503a57d8d4def5cc/tools/lexer/jflex-1.7.0-SNAPSHOT.jar) I downloaded from https://github.com/JetBrains/intellij-community/commit/b7f882a7a99554e7e3b9cdbf503a57d8d4def5cc
2. debugging shows that the very first call to `scanner.advance()` reaches `boolean eof = zzRefill();` and `zzRefill()` unconditionally returns true, which pushes me into the EOF state and aborts parsing. What jflex-skeleton file are you using? Because contrary to [the upstream one](https://github.com/jflex-de/jflex/blob/master/jflex/src/main/resources/jflex/skeleton.default#L93), the one [in grammar-kit](https://github.com/JetBrains/intellij-community/blob/master/tools/lexer/idea-flex.skeleton#L89) has that noop-`zzRefill()` implementation. It even shows me in my generated scanner file, that `private java.io.Reader zzReader;` is assigned (in the ctor) but never used

**Comment by gregsh** [comment]
I used [community/tools/lexer/idea-flex.skeleton](https://github.com/JetBrains/intellij-community/blob/master/tools/lexer/idea-flex.skeleton)

**Comment by stefansjs** [comment]
I have the same issue. The issue is obviously that the lexer never reads the input file. I believe this section in main is the culprit

```
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new ChuckLexer(reader);
          do {
            System.out.println(scanner.advance());
          } while (!scanner.zzAtEOF);
```

The constructor of the lexer assigns the reader, but the advance() method never references the lexer (nor any other method)
