### ISSUE TITLE
Empty string not handled

### ISSUE THREAD

**Issue by FatalCatharsis** [JetBrains/Grammar-Kit#150]
I've tried a few different ways to accept empty string without consuming a token with no success. I am trying to write a grammar for a language that had lot's of direct left recursion. To do the necessary recursion elimination to gen the LL parser, I need the ability to handle empty string but I did not find any mention in the documentation. The ideas I thought of are:

```
PostfixExpressionPrime ::=
    ("." IDENTIFIER PostfixExpressionPrime) |
    ("." TemplateInstance PostfixExpressionPrime) |
    ("." NewExpression PostfixExpressionPrime) |
    ("++" PostfixExpressionPrime) |
    ("--" PostfixExpressionPrime) |
    ("(" ArgumentList? ")" PostfixExpressionPrime) |
    IndexExpression |
    SliceExpression |
```

with the extra empty bar on the end or:

```
PostfixExpressionPrime ::=
    ("." IDENTIFIER PostfixExpressionPrime) |
    ("." TemplateInstance PostfixExpressionPrime) |
    ("." NewExpression PostfixExpressionPrime) |
    ("++" PostfixExpressionPrime) |
    ("--" PostfixExpressionPrime) |
    ("(" ArgumentList? ")" PostfixExpressionPrime) |
    IndexExpression |
    SliceExpression |
    ""
```

with the empty quotes. Both return false on the generated empty token check. If this capability does not exist, then this is a feature request, else this is just an easy question.

**Comment by FatalCatharsis** [comment]
btw, the workaround was to just do this:

PostfixExpressionPrime ::=
   ( ("." IDENTIFIER PostfixExpressionPrime) |
    ("." TemplateInstance PostfixExpressionPrime) |
    ("." NewExpression PostfixExpressionPrime) |
    ("++" PostfixExpressionPrime) |
    ("--" PostfixExpressionPrime) |
    ("(" ArgumentList? ")" PostfixExpressionPrime) |
    IndexExpression |
    SliceExpression)?

**Comment by gregsh** [comment]
Please ask questions on [JetBrains plugin developers forum](https://intellij-support.jetbrains.com/hc/en-us/community/topics/200366979-IntelliJ-IDEA-Open-API-and-Plugin-Development). You'll get answers there much faster than here.
