### ISSUE TITLE
Removing minus from a grammar affects parsing of a plus expression

### ISSUE THREAD

**Issue by LogvinovLeon** [JetBrains/Grammar-Kit#153]
Here is the smallest example that I was able to produce.

On the right side is a simple expression grammar, which has + and -. It parses 1+1 correctly.
On the left side is even more simple grammar without -. It says that + is unexpected.
<img width="947" alt="screen shot 2017-02-19 at 20 22 31" src="https://cloud.githubusercontent.com/assets/6204356/23105561/7d17cac6-f6e1-11e6-9df4-3ec4e5afa0fb.png">

Can someone explain, why is it so?

**Comment by gregsh** [comment]
Thanks, that was a really well-hidden bug that survived many versions and tests!
