### ISSUE TITLE
A pair of braces affects Endless recursion

### ISSUE THREAD

**Issue by LogvinovLeon** [JetBrains/Grammar-Kit#154]
The only difference between the grammar on the left and on the right is the pair of braces in line 15.
Can someone explain, why those braces solve the Endless recursion issue?
![screen shot 2017-02-20 at 17 13 42](https://cloud.githubusercontent.com/assets/6204356/23133049/f959770c-f78f-11e6-9321-7a6e91b127dd.png)

**Comment by gregsh** [comment]
Sure. Check the QuickDoc for *TupleExpression* rule.
On the left it shall be *BINARY* operator, on the right it is *ATOM*.
```
TuplleExpression ::= Expression (',' Expression?)   // POSTFIX operator
TuplleExpression ::= Expression (',' Expression) +   // N-ARY operator
```
