### ISSUE TITLE
Predicate rules do not report errors with consumeTokenFast

### ISSUE THREAD

**Issue by matklad** [JetBrains/Grammar-Kit#158]
Consider the following grammar:

```
{
  consumeTokenMethod(".*") = "consumeTokenFast"
}

File ::= Foo &Bar {pin=1}

Foo ::= "foo"
Bar ::= "bar"
```

For the file `foo`,  the Psi tree does not contain any error elements, although there is no `bar` after `foo` and predicate `&Bar` fails. 

Note that `consumeTokenFast` bit is important: without it, I do get an error. 

I think that `consumeTokenMethod` should not change the set of files parsed without errors. Or is this intentional?

The real world example of this issue happens in the following grammar for comma separated lists with an optional trailing comma:

```
File ::= '(' ListItem* ')'
private ListItem ::= 'x' (',' | &')') {pin=1}
```

There are no errors reported for `(x, x x, x)`.

**Comment by jvolkman** [comment]
I can't reproduce this in live preview. I get the error "')' or ',' expected, got 'x'". Maybe some other part of your grammar is interfering?

**Comment by calexHG** [comment]
Actually, I wasn't surprised to read of a lack of errors.. but, as with Jeremy, I cannot reproduce that error either, even after updating my GK fork from 1.5.0 to 1.5.1 to see if that was causing the difference.

Do you get no errors reported even with your posted example rules being placed at the root of your grammar? Is your predicate getting nested within another?

> IntelliJ IDEA 2017.1
> Build #IC-171.3780.52, built on March 14, 2017

**Comment by matklad** [comment]
@jvolkman @calexHG thank you for looking into this issue! Turns out there is one more crucial ingredient here: `consumeTokenMethod` should be `Fast`. I've updated the issue description.

**Comment by gregsh** [comment]
Fast method do not add any error-reporting info, this is how it is.

**Comment by calexHG** [comment]
@gregsh =p

@matklad I understand your situation in that what one might expect is an error that lacks any "expected" info; not the absence of any error at all. 

From my experience, changing the operation of that with a blanket consumeTokenMethod attribute change is too simplistic an attempt and does not get the results that that attribute seemingly intended to deliver once upon a time.
