### ISSUE TITLE
GrammarKit generates not compilable code

### ISSUE THREAD

**Issue by slavam2605** [JetBrains/Grammar-Kit#159]
I use GrammarKit 1.5.1 plugin and generate java class with Ctlr+Shift+G.
I have Grammar-Kit.jar and light-psi-all.jar in my classpath.
But in generated code I have this import:
`import static com.intellij.lang.parser.GeneratedParserUtilBase.*;`
And there is no such package/class in my jars. But this class is actually located in:
`import static org.intellij.grammar.parser.GeneratedParserUtilBase.*;`.

What shoud I do to generate classes properly?

**Comment by gregsh** [comment]
It is in Intellij SDK:
https://github.com/JetBrains/intellij-community/blob/master/platform/lang-impl/src/com/intellij/lang/parser/GeneratedParserUtilBase.java

One can use either platform version mentioned above or its own version.
To use own version just copy platform or Grammar-Kit version to a project sources.
