### ISSUE TITLE
Question: Typescript files

### ISSUE THREAD

**Issue by mendrik** [JetBrains/Grammar-Kit#163]
Any idea why I cannot see the structure for typescript files?

**Comment by gregsh** [comment]
Please attach some screenshots.

**Comment by mendrik** [comment]
![image](https://user-images.githubusercontent.com/160805/29782205-556ee990-8c24-11e7-944a-8d02608e1578.png)

As you can see for my typescript files both actions are not available

**Comment by gregsh** [comment]
Not sure. Here's the code, though:

https://github.com/JetBrains/intellij-community/blob/65827cce2386de4b1135f7db6c50428cb5f70d97/platform/lang-impl/src/com/intellij/internal/psiView/PsiViewerAction.java#L43

**Comment by gregsh** [comment]
I'm closing this as not related to Grammar-Kit. 
Please direct further questions to IDEA issue tracker at http://youtrack.jetbrains.com .
