### ISSUE TITLE
PsiViewer: support modified PSI (via TemplateDataElementType.appendCurrentTemplateToken)

### ISSUE THREAD

**Issue by azrdev** [JetBrains/Grammar-Kit#164]
The language I'm implementing is a grammar, whose constructs (with embedded "outer language" java/c++/… fragments) get translated into functions of the outer language, with contain those fragments. I'm successfully merging both with a `MultiplePsiFilesPerDocumentFileViewProvider`, but for the outer language to see a valid file (e.g. for java no functions outside a class), I have to inject text which isn't really there. This works so far using `TemplateDataElementType.appendCurrentTemplateToken`, however in the PsiViewer this invisibly moves the TextRanges of selected elements, i.e. an insertion of "sometext" will highlight the 8 characters *after* the place where it is (invisibly) inserted, and these offsets add up.

Also, the context menu actions "PSI dump to clipboard" only work for the base language, but I'd benefit from seeing the PSI like the template/outer language does.

**Comment by gregsh** [comment]
Please create a ticket in IntelliJ IDEA issue tracker at http://youtrack.jetbrains.com .
This is not related to Grammar-Kit plugin.

**Comment by calexHG** [comment]
Hey @azrdev. Congrats on successfully dealing with some of the less basic PSI usage patterns. I should note, though, that PsiViewer is not actually a part of Grammar-Kit.

Depending on which PSI viewer tool you're referring to, it sounds like the official places to resolve the problem you're having will be  either of the following two sets of pages:
- [IntelliJ IDEA’s issue tracker](//youtrack.jetbrains.com) and/or 
[the IntelliJ Platform development forum](https://intellij-support.jetbrains.com/hc/en-us/community/topics/200366979-IntelliJ-IDEA-Open-API-and-Plugin-Development)
- the 3rd-party "PsiViewer" plugin's [issue tracker](//github.com/cmf/psiviewer/issues)

**Comment by calexHG** [comment]
(whoops. reply was made redundant sometime before sending it.)

**Comment by azrdev** [comment]
Sorry, should have looked that up beforehand. Thanks for the redirections!

@calexHG I didn't know about https://github.com/cmf/psiviewer, what's its difference/benefit over the builtin one?

**Comment by calexHG** [comment]
@azrdev 
I wrote a long pro–con description list that included, most importantly, the reason I no longer use it, but lost that post in an app crash just now. That is biggest pet peeve. Frustrating. 

Oh well. At least it now seems that the pros part of that list wasn't necessary. Cheers!
