### ISSUE TITLE
JFlex doesn't see pre-installed JARs, tries to download non-existing JARs

### ISSUE THREAD

**Issue by endlos99** [JetBrains/Grammar-Kit#165]
For compatibility, I'm using an older version of IDEA and Grammar-Kit. When running JFlex, it tries to download one non-existing file:

   https://github.com/JetBrains/intellij-community/raw/master/tools/lexer/jflex-1.4/lib/JFlex.jar

Manually downloading another version and renaming it to JFlex.jar will not stop this behavior.

Thus, either the existence detection is broken, or the download target should be configurable, or downloads should be downwards compatible (preferred).

**Comment by gregsh** [comment]
Please always use the latest versions of plugins and JetBrains tools.
Here's the [current version code](
https://github.com/JetBrains/Grammar-Kit/blob/master/src/org/intellij/grammar/actions/BnfRunJFlexAction.java#L96)

**Comment by MorganRamsay** [comment]
```
  private static final String[] JETBRAINS_JFLEX_URLS = {
      "https://github.com/JetBrains/intellij-community/raw/master/tools/lexer/jflex-1.7.0-SNAPSHOT.jar",
      "https://raw.github.com/JetBrains/intellij-community/master/tools/lexer/idea-flex.skeleton"
  };
```
The first URL links to a nonexistent file, so trying to run the JFlex parser produces this error:


> Failed to download 'https://github.com/JetBrains/intellij-community/raw/master/tools/lexer/jflex-1.7.0-SNAPSHOT.jar':
> Status: 404

**Comment by gregsh** [comment]
@MorganRamsay Thanks, I am aware of the change.
Will update GK shortly.

**Comment by BuDashka** [comment]
> * Go to **Help | Edit Custom VM Options**

Hello!
It still doesn't work for me. Can you please explain more detailed how to generate lexer with JFlex (step by step). I am using:
MacOS 10.13.6; 
IntelliJ IDEA 2016.3.4
Build #IC-163.12024.16, built on January 31, 2017
JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Writing a plugin for Refal 5λ

Thank you in advance!
@chashnikov  @gregsh
