### ISSUE TITLE
Cannot run custom language plugin as test

### ISSUE THREAD

**Issue by endlos99** [JetBrains/Grammar-Kit#166]
I develop a custom language plugin in the latest IDEA Community Edition that builds and prepares fine.
When I Run this plugin from IDEA, this will launch a second instance.  But when I create or open a project with the second instance, the second instance aborts with this error message:

    Fatal error initializing 'com.intellij.codeInsight.daemon.impl.DaemonListeners'

This seems irrespective of which plugins are activated.

**Comment by endlos99** [comment]
I've just realized that this error is caused by my plugin.
But why if there are no compile errors?

**Comment by gregsh** [comment]
Logs shall contain the full stack trace for the error.
Otherwise it's hard to tell for sure.

**Comment by endlos99** [comment]
But where are the logs? In the forum, someone suggested the Help menu, but I'm stuck on the "Welcome to IntelliJ IDEA" welcome screen, which doesn't have a proper Help menu.
"Create new project" does nothing, "Open" will only display the above error message.
Where are the logs for a test instance started by Run -> Run 'Plugin'?
When I delete .IdeaIC2017-2/system/log/idea.log and do my little maneuver, it won't be recreated.

**Comment by gregsh** [comment]
https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs

**Comment by endlos99** [comment]
My apologies, I found the log settings in the Run Configuration.
This procedure
1. using Run to start a second IDEA with the custom plugin activated,
2. clicking "create project" (doing nothing),
3. clicking "Open ..." and selecting a folder (showing the error message)
yields this log:
```
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=250m; support was removed in 8.0
(java:1340): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
(java:1340): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
```
The plugin was developed with IDEA-2016-2 is now extended with IDEA-2017-2.

**Comment by gregsh** [comment]
Here's what I've just google'd:
https://forum.manjaro.org/t/intellij-idea-pycharm-not-working/9023/4

**Comment by endlos99** [comment]
Thanks for the link, but I'm not really concerned about the GTK warnings. I'm also not using a tiled window manager, like in the ticket, but I tried anyway and it didn't work.

The real issue here is that I cannot start a functioning IDEA and only get a popup window with above error message when I launch an IDEA with my plugin enabled.

**Comment by endlos99** [comment]
Version 2016-3 shows the same behavior. I cannot test the original version 2016-2 any more as the required JFlex.jar is missing and cannot be installed.

**Comment by endlos99** [comment]
I'm not sure if this is helpful, but here is the master log of 2017-2, containing at least the build of the plugin, running (unsuccessfully) the plugin, installing the plugin in the main IDEA, and starting the main IDEA (unsuccessfully) twice.
[log.zip](https://github.com/JetBrains/Grammar-Kit/files/1295952/log.zip)

**Comment by gregsh** [comment]
There's one fatal error in the log:
```
Caused by: java.lang.AssertionError
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl.loadAdditionalTextAttributes(EditorColorsManagerImpl.java:276)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl.initDefaultSchemes(EditorColorsManagerImpl.java:164)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl.<init>(EditorColorsManagerImpl.java:143)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
```
Place breakpoint there and see what scheme cannot be found.

**Comment by endlos99** [comment]
Thanks, that was it!  It didn't find my additionalTextAttributes file, as I didn't know where its path was relative to.
Also, I'm not sure if assert != null is the best way to handle a file not found, instead of just skipping it.
I'll leave this issue open In case you do want to change this behavior, otherwise please just close it.

**Comment by endlos99** [comment]
Never mind, I forgot this is the plugin project. :-)

**Comment by gregsh** [comment]
Assert is certainly an awful way to report such errors.
[I've already dropped it.](https://github.com/JetBrains/intellij-community/commit/33dadd31ebb10f65f5e158a4c6e0c522ceb2b3d3#diff-be246cba882d083ad55793672eedb0a8)

**Comment by endlos99** [comment]
Awesome! :-)
