### ISSUE TITLE
Standalone usage

### ISSUE THREAD

**Issue by mayakwd** [JetBrains/Grammar-Kit#167]
It's not possible to use newer versions of grammar-kit in standalone way, as described [here](https://github.com/JetBrains/Grammar-Kit#standalone-usage).

It's always can't find some classes, light-psi-all.jar seems doesn't match to current code.
My tries to run LightPsi-All: Package haven't got any success (Intellij Idea 2017.2.4). Is there are any proven method to make it works?

**Comment by gregsh** [comment]
Just add idea jars (idea.jar, openapi.jar, util.jar) to classpath.
See my comment in https://github.com/JetBrains/Grammar-Kit/issues/41.

**Comment by mayakwd** [comment]
Tried to do so today, it won't help at all, some classes from guava required too, but grammar-kit can't find it.

**Comment by gregsh** [comment]
I got it. Looks like one has to add guava.jar to META-INF/MANIFEST and classpath then.
Otherwise one can run via `java -cp ... ` instead of `java -jar ...`.

**Comment by gregsh** [comment]
I've updated MANIFEST.MF and *Standalone usage* section.
Seems it is working for now for the dev build.

**Comment by 62mkv** [comment]
Hi @gregsh is `Standalone section` still valid? 2019.3 zip (from https://github.com/JetBrains/Grammar-Kit/releases) does not seem to contain anything like `light-psi-all.jar`. There's nothing in `MANIFEST.MF` also (just a `Manifest-Version: 1.0` line). and if I try to run `java -jar grammar-kit-2019.3.jar gen mysyntax.bnf` I get `no main manifest attribute, in grammar-kit-2019.3.jar`

what am I doing wrong?
