### ISSUE TITLE
Options.GEN_JFLEX_ARGS cause encoding wrong in windows

### ISSUE THREAD

**Issue by zxj5470** [JetBrains/Grammar-Kit#172]
[Options.java](https://github.com/JetBrains/Grammar-Kit/blob/master/src/org/intellij/grammar/config/Options.java
)
```java
  Getter<String> GEN_JFLEX_ARGS = Option.strOption("grammar.kit.gen.jflex.args", "");
```
[BnfRunJFlexAction.java](https://github.com/JetBrains/Grammar-Kit/blob/master/src/org/intellij/grammar/actions/BnfRunJFlexAction.java)
```java
SimpleJavaParameters javaParameters = new SimpleJavaParameters();
      Sdk sdk = new SimpleJavaSdkType().createJdk("tmp", SystemProperties.getJavaHome());
      javaParameters.setWorkingDirectory(workingDir);
      javaParameters.setJdk(sdk);
      javaParameters.setJarPath(jflex.get(0).getAbsolutePath());
      javaParameters.getVMParametersList().add("-Xmx512m");
      javaParameters.getProgramParametersList().addParametersString(StringUtil.nullize(Options.GEN_JFLEX_ARGS.get()));
      javaParameters.getProgramParametersList().add("-skel", jflex.get(1).getAbsolutePath());
      javaParameters.getProgramParametersList().add("-d", VfsUtil.virtualToIoFile(virtualDir).getAbsolutePath());
      javaParameters.getProgramParametersList().add(flexFile.getName());
```

File encoding is utf-8 and under Linux and Mac ,and the command below is `-Dfile.encoding=UTF-8`

But in windows,the command is :
```
java -Xmx512m -Dfile.encoding=GBK -jar path/to/jflex-1.7.0.jar -skel path/to/idea-flex.skeleton ..........
```
in windows 
even though I can run a command instead it by manual but never generate a xxxLexerAdapter.java

## Can there be some configurable in Settings(Preference) to set args?

**Comment by gregsh** [comment]
Options.GEN_JFLEX_ARGS are not to blame. Encoding is set by [JdkUtil](https://github.com/JetBrains/intellij-community/blob/master/platform/lang-api/src/com/intellij/openapi/projectRoots/JdkUtil.java#L444) code.

Now the encoding is explicitly set to the .flex encoding.
Try the latest dev build with this fix (install via Settings | Plugins | Install from Disk).

https://teamcity.jetbrains.com/viewType.html?buildTypeId=IntellijIdeaPlugins_GrammarKit_Build
