### ISSUE TITLE
Handling right-associative left-recursion

### ISSUE THREAD

**Issue by ice1000** [JetBrains/Grammar-Kit#173]
See this line:

https://github.com/JetBrains/intellij-plugins/blob/master/Dart/src/com/jetbrains/lang/dart/Dart.bnf#L530

Say, if I use the approach described in https://github.com/JetBrains/Grammar-Kit/blob/master/TUTORIAL.md (instead of the very complex approach discussed in #95 ), How can I make a right-associative expression parsed?

Also, how does `left` work as a rule modifier..

**Comment by gregsh** [comment]
> Also, how does left work as a rule modifier..

`(node) (rule)    vs    ((node) left_rule)    vs    (node (inner_left_rule))`

>  How can I make a right-associative expression parsed?

Via right recursion, I guess:

```
private assignExpressionWrapper ::= ternaryExpressionWrapper assignExpression*
left assignExpression ::= assignmentOperator assignExpressionWrapper {pin=1}
```

**Comment by ice1000** [comment]
Thanks :)
