### ISSUE TITLE
[ bug ] BNF about `expr+` and `expr*` and `expr expr*`

### ISSUE THREAD

**Issue by zxj5470** [JetBrains/Grammar-Kit#175]
I'm developing [julia-intellij plugin](https://github.com/ice1000/julia-intellij) and we have code to parse like this
```julia
name = @macro funcall()
```

`@macro funcall()`'s BNF:

```
applyMacroOp ::= macroSymbol expr expr*     // BUG: `expr+` is useless, and I don't know why~
```
`macroSymbol` is `@`+ symbol

But neither `expr+` nor `expr*` is useful...
only to write  stupid code `expr expr*`

**Comment by gregsh** [comment]
Expression grammar is a special case and treated a bit differently than ordinary BNF.
The BNF expression is matched against the following patterns: 
A -- atom, op A -- prefix operator, A op B -- binary operator, A (op B)+ -- n-ary operator.
where A is an expression root rule or any of its descendants.

You can always use *Quick Documentation* (Control-Q / Control-J on macOS) to see how a specific rule is interpreted. 

Here:
`applyMacroOp ::= macroSymbol expr expr*` is interpreted as ATOM, so it's parsed as ordinary BNF.
`applyMacroOp ::= macroSymbol expr+` on the other hand is a POSTFIX operator
