### ISSUE TITLE
Support generation of token types without definition

### ISSUE THREAD

**Issue by alexei-osipov** [JetBrains/Grammar-Kit#179]
Please add generation of tokens without definition. This is needed to define some special token types when there are external lexer used.

`my.bnf`:
```
{
  tokens=[ token-one token-two ]
}
```
Right now the GrammarKit accepts such BNF as valid but does not generate definitions (constants in "elementTypeHolderClass") for these tokens.

**Comment by alexei-osipov** [comment]
Note: existing test data contains "PsiAccessors.bnf" that has token "nodef". The token is mentioned in a fake rule and not included in the generated "elementTypeHolderClass".

**Comment by gregsh** [comment]
Please describe the use case so I can get it. ;-)

**Comment by alexei-osipov** [comment]
Use case:
I want to have INDENT and DEDENT tokens for Python-like language.
Both tokens are not explicitly mentioned in the Grammar because they are parsed using `external` method. So there is no direct reference from the grammar. However I still want to have both tokens in the generated "elementTypeHolderClass".

**Comment by alexei-osipov** [comment]
Upd:
Found a way to get what I needed using
```
{
  tokens=[
    token-one="token-one"
    token-two="token-two"
  ]
}
```
So the issue can be closed.

**Comment by gregsh** [comment]
Ok, thanks.
