### ISSUE TITLE
Unexpected parsing error

### ISSUE THREAD

**Issue by akornev** [JetBrains/Grammar-Kit#180]
Given the BNF
```
{
  tokens=[    
    whitespace='regexp:\s+'    
    id='regexp:\p{Alpha}\w*'
  ]
}

root ::= ruleA? ruleB* ruleC*

ruleA ::= modifier? keyword1 id
ruleC ::= modifier? keyword2 id
ruleB ::= keyword3 id {pin=1 recoverWhile=ruleB_recover}
private ruleB_recover ::= !(keyword2|modifier)

private modifier ::= mod1 | mod2
```
produces a parsing error for the following input:
```
mod1 keyword2 foo
```
The error only appears when the `recoverWhile` attribute in `ruleB` is present.
![screen shot 2018-04-22 at 10 01 55 am](https://user-images.githubusercontent.com/1650235/39097672-431f7840-4614-11e8-9805-133ed075deff.png)

**Comment by gregsh** [comment]
That is how recoverWhile works. The recovery procedure takes place **regardless** of whether the rule succeeds or not.

See https://github.com/JetBrains/Grammar-Kit/blob/master/HOWTO.md#22-using-recoverwhile-attribute

**Comment by akornev** [comment]
I understand. But as it defined, shouldn't `ruleB_recover` stop skipping tokens once it hit a `modifier`?

**Comment by akornev** [comment]
If you don't mind, this is not at all obvious (to me) how to achieve the desired outcome, and I'd really appreciate if you could give me a hint. 😀

**Comment by gregsh** [comment]
Yes, here's the flag logic:
https://github.com/JetBrains/Grammar-Kit/blob/master/src/org/intellij/grammar/parser/GeneratedParserUtilBase.java#L562

"recoverWhile" advances in human terms if the frame does not advance at all and the error is present someplace after. The doc I referenced says one usually has to use "pin".
