### ISSUE TITLE
Generation error

### ISSUE THREAD

**Issue by leus** [JetBrains/Grammar-Kit#182]
Hello,

I'm following the tutorial here and I'm getting an error on the generated code:

```
// This is a generated file. Not intended for manual editing.
package org.tutorial.psi;

import java.util.List;
import org.jetbrains.annotations.*;
import com.intellij.psi.PsiElement;

public interface MyPlaceHolder extends PsiElement {

  @NotNull
  PsiElement getText();

}
```
The compiler throws the following error:

>     Error:(11, 14) java: getText() in org.tutorial.psi.MyPlaceHolder clashes with getText() in com.intellij.psi.PsiElement
>     return type com.intellij.psi.PsiElement is not compatible with java.lang.String
> 

My project SDK is configured with "IntelliJ IDEA Community Edition IC-181.4203.550", which contains the following code in the base class (which also matches the code in the idea repo):
```
  /**
   * Returns the text of the PSI element.
   *
   * @return the element text.
   */
  @NonNls
  @Contract(pure=true)
  String getText();
```
If I change the element in my BNF from
```
placeHolder ::= '[' text ']'
```
to
```
placeHolder ::= ( '[' text ']' ) *
```
it generates valid code, but then my definition fails somewhere else (and I'm concerned with the correctness of the generated code).

Any hints?

**Comment by gregsh** [comment]
One can use **methods** attribute for that, see
https://github.com/JetBrains/Grammar-Kit/blob/master/resources/messages/attributeDescriptions/methods.html#L27
