### ISSUE TITLE
No stub constructor is generated if element extends other element

### ISSUE THREAD

**Issue by huangyg11** [JetBrains/Grammar-Kit#192]
In bnf:

```
{
  extends(".*Expression")=Expression
}
.
.
.
Expression ::=
   FunctionCallExpression  | IndexAccessExpression | ParenExpression

FunctionCallExpression ::= (Identifier '(' FunctionCallArguments? ')') |
                           ( ( PrimaryExpression | NewExpression | TypeName  ) ( ( '.' Identifier ) | ( '[' Expression? ']' ) )* '(' FunctionCallArguments? ')' )  {
    implements = "me.serce.solidity.lang.psi.SolReferenceElement"
    mixin = "me.serce.solidity.lang.psi.impl.SolFunctionCallElement"
    stubClass = "me.serce.solidity.lang.stubs.SolFunctionCallExpressionStub"
}
```

In the generated SolFunctionCallExpressionImpl.java, there is only one constructor, no stub generator. 

If I remove the extends statement in the bnf, it does generate two constructor in the java file.

Don't know if this behaviour is intended or is just a bug?

If it is intended, how do make it generate the stub generator without removing the extends statement?

Thanks

**Comment by gregsh** [comment]
Stub-based PSI and AST-wrapper PSI are completely different class (not interface) hierarchies.
Super-classes are StubBasedPsiElementBase and ASTWrapperPsiElement.

To fix that: add stub attribute to Expression too.

Also: it's rare for expression to need stubs. Stubs are used for structural indices to avoid costly parsing on operations like "Go to class/symbol" navigation and to quickly resolve across files.
