### ISSUE TITLE
Is it possible to highlight a parsing rule?

### ISSUE THREAD

**Issue by clicman** [JetBrains/Grammar-Kit#203]
From the documentation, I can see how to highlight token., But how can I highlight a parser rule?
Example:

    {
        [
            word="regexp:\w+"
            COLON=":"
        ]
    }
    root ::= need_highlighting
    need_highlighting ::= word COLON [word]

How to highlight a `need_highlighting` in such syntax?

**Comment by clicman** [comment]
Okay. Found it.

**Comment by ice1000** [comment]
What did you find?
