### ISSUE TITLE
Allow specifying the start set of an external rule

### ISSUE THREAD

**Issue by oowekyala** [JetBrains/Grammar-Kit#207]
External rules may have a known start set, but AFAIK there's currently no way to make the code generator aware of it. That causes trouble e.g. when using the auto recoverWhile for a rule if its follow set contains an external rule. Btw this case isn't currently handled as an error, but the generated code doesn't compile. It produces something like that:
```java
  static final Parser X_auto_recover_ = (builder_, level_) -> !nextTokenIsFast(builder_, ); // nothing in the second argument
```    

I think it would be reasonable to allow specifying the start set using a dummy private rule. E.g.:
```
external block      ::= eatUpToMatchingBrace { startRule=block_start }
private block_start ::= "{" // the start set of this rule is used as the start set of the "block" rule
```
Generating an auto recover predicate when the follow set contains an external rule which doesn't specify its start set should probably throw an error. Wdyt? 

Note: I found that currently the following workaround may be used in some cases to preserve the start set:
```
block              ::= "{" ext_block
external ext_block ::= eatUpToMatchingBrace
```
This is fine but the first "{" token has been already consumed when entering the external code. That means the external code must adapt to that, which is not always possible - you need full control over the external code.

**Comment by gregsh** [comment]
I'd use the following:
```
block              ::= &"{" ext_block
external ext_block ::= eatUpToMatchingBrace
```
