### ISSUE TITLE
allow specifying case sensitivity for match by text

### ISSUE THREAD

**Issue by jregistr** [JetBrains/Grammar-Kit#209]
I found a case where I'm experiencing an ambiguity due to different rules having lower case and upper case versions of the same text.

For example, take the simple grammar
```text
{
tokens=[
WHITE_SPACE = 'regexp:\s+']
}
Document ::= Statement*

Statement ::= 'foo' | 'bar' | 'baz'
```
This would match for `foo` as well as `FOO`.

**Comment by gregsh** [comment]
One currently has 2 options:

1. Declare the language case-sensitivity via `Language#isCaseSensitive` (preferred)
2. Use custom `parserUtilClass` with a tweaked `nextTokenIsFast(builder, text, caseSensitivity)` method or its callers.
