### ISSUE TITLE
Parse errors as a configurable inspection

### ISSUE THREAD

**Issue by carymrobbins** [JetBrains/Grammar-Kit#220]
Is there any way to control how and if parse errors appear in the source? I imagine this possibly being an inspection that can be set to a certain error level or maybe even turned off. Reason being that some languages seem to move quickly and keeping up with all the new grammar rules can be tough.

Is there an existing way to do this, or would this need to be a new feature?

**Comment by gregsh** [comment]
Syntax errors are actual PsiErrorElement AST nodes and not inspections (which are configurable).
`com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor` creates ERROR highlighting for them in a non-configurable manner. Check out
`com.intellij.codeInsight.highlighting.HighlightErrorFilter` to completely suppress them.

**Comment by carymrobbins** [comment]
Does this mean that there might be some way to supply a different `HighlightVisitor` implementation that could do something different?

**Comment by gregsh** [comment]
No, there's none. I mentioned it so that one could check it in IDEA Community sources on GitHub.

**Comment by carymrobbins** [comment]
Ok, so I take it you _can_ do it, you just need to implement your own `HighlightVisitor`. In this case, that may be overkill. Thanks for the help!
