### ISSUE TITLE
Regular expressions become invisible in the current line

### ISSUE THREAD

**Issue by rillig** [JetBrains/Grammar-Kit#226]
I'm writing a grammar in IntelliJ using the Darcula theme:

![image](https://user-images.githubusercontent.com/3233724/72376373-218a4100-370e-11ea-8558-e11882df899a.png)

The regular expressions are nicely distinguished from the other text by using a different background color.

But when I navigate to one of these lines, the highlighting disappears:

![image](https://user-images.githubusercontent.com/3233724/72376779-d886bc80-370e-11ea-98c3-992de30db999.png)

Apparently the "current line" background color is stronger than the "regular expression" background color.

This is especially confusing when I start typing such a string literal. Assume that I'm starting with `T_NL = ""` and then slowly type `regexp:\n`. I won't notice that I'm entering RegExp mode in the editor since nothing changes visually. Well, almost nothing. The font gets bold, but that's such a subtle difference that I didn't notice it.

**Comment by gregsh** [comment]
That shall go to https://youtrack.jetbrains.com/issues/IDEA .
