### ISSUE TITLE
Bad example in help for tokens

### ISSUE THREAD

**Issue by rillig** [JetBrains/Grammar-Kit#227]
The quick documentation for `tokens` says:

~~~text
Examples:
  {
    tokens = [
      id="regexp:\w+"    // regexp token
      string             // no value or pattern

      PLUS_OP="+"
      SWITCH="switch"
    ]
  }
~~~

I took this grammar and added the following productions:

~~~text
file ::= token*
token ::= id | string | PLUS_OP | SWITCH
~~~

Then I tried the grammar using this file:

~~~text
hello+switch
~~~

Both `hello` and `switch` are parsed as `id`. I had expected `switch` to be parsed as `SWITCH` since there is a separate token definition for it. The example should be fixed so that `switch` is not parsed as an identifier.

**Comment by gregsh** [comment]
Works as expected now.
