### ISSUE TITLE
Issues with Grammar-Kit 2019.3 and IntelliJ IDEA 2020.1 EAP

### ISSUE THREAD

**Issue by SCWells72** [JetBrains/Grammar-Kit#230]
I'm logging this issue after discussing the associated problems with @YannCebron on the JetBrains Platform `intellij-platform` Slack channel.

I use Grammar-Kit to build my custom language plugin. I've been doing so for ~5 years. Yesterday I decided to update my plugin as necessary for the changes in 2020.1 EAP. That went generally quite well. I did have to update my ant build (yes, I haven't been able to move to Gradle yet...) to include two additional jars that aren't in Grammar-Kit's `META-INF/MANIFEST.MF`, `platform-concurrency.jar` and `testFramework.jar`. With those added, the parsers are successfully generated. However, I do see the following output when doing so:

```
     [java] WARN: The registry key 'psi.track.invalidation' accessed, but not loaded yet
     [java] WARN: The registry key 'psi.incremental.reparse.depth.limit' accessed, but not loaded yet
```

The resulting parsers seem fine, so this could just be noise, but given that it's a behavioral change I wanted to log it here so that it can be researched. It seems that minimally the `META-INF/MANIFEST.MF` needs to be updated for a version that works out-of-the-box with 2020.1 (EAP?).

Let me know if you need any other info.

**Comment by gregsh** [comment]
Thanks, `META-INF/MANIFEST.MF` updated.

As for the warnings, they are produced by IntelliJ Platform, not GK.
Don't think there's a way to suppress them now.
