### ISSUE TITLE
Can we use several psiImplUtilClass at one time?

### ISSUE THREAD

**Issue by XenoAmess** [JetBrains/Grammar-Kit#232]
If so, then how?

**Comment by gregsh** [comment]
Currently `psiImplUtilClass` is global and can be specified only for all rules at once.

But you can split methods between abstract classes so that all the methods could be accessed via the top inheritor, e.g.:
```
public class Base1 {
// ... static methods
}
public class Base2 extends Base1 {
//... static methods
}
public class MyPsiImplUtil extends Base2 {
// can even be empty.
}
```

Unfortunately static methods in interfaces cannot be used.
