### ISSUE TITLE
Allow specifying different psiImplUtilClass for element

### ISSUE THREAD

**Issue by mar-v-in** [JetBrains/Grammar-Kit#237]
It would be great if one could specify `psiImplUtilClass` per element or for multiple elements using the existing syntax.
```
{
  psiImplUtilClass='com.example.psi.PsiImplUtil'
  psiImplUtilClass(".*Expression")='com.example.psi.ExpressionImplUtil'
  extends(".+Expression")=Expression
  extends(".+Statement")=Statement
}
File ::= Statement*
Statement ::= PrintStatement | AssignmentStatement
PrintStatement ::= 'print' Expression ';'
VariableDeclaration ::= Name {
  implements=['PsiNamedElement', 'PsiNameIdentifierOwner']
  methods=[getName, setName, getNameIdentifier]
  psiImplUtilClass='com.example.psi.VariableImplUtil'
}
AssignmentStatement ::= VariableDeclaration '=' Expression ';'
Expression ::= BinaryExpression | LiteralExpression | VariableAccessExpression {
  methods=[evaluate]
}
BinaryExpression ::= Expression BinaryOp Expression
LiteralExpression ::= Literal
VariableAccessExpression ::= Name {
  implements=['PsiReference']
  methods=[getReference]
  psiImplUtilClass='com.example.psi.VariableImplUtil'
}
```

This way I can split my psiImplUtilClass into three:
- `PsiImplUtil` (default)
- `VariableImplUtil` (for `VariableAccessExpression` and `VariableDeclaration`)
- `ExpressionImplUtil` (for those matching regex `.*Expression"`)

Allowing me to have smaller and cleaner files. Currently splitting implementations across files requires using mixins, which isn't always very feasible.

Related #132 

Note: Alternatively, proper support for Kotlin (#212) could be introduced, allowing to make use of functions declared across multiple files in the same namespace.

**Comment by gregsh** [comment]
One can split util classes as they wish, and then in a grammar file use the one that extends all of them.
That shall solve the problem of large files.
