### ISSUE TITLE
extends(expr) sub rule which had > 2 recurses fails

### ISSUE THREAD

**Issue by AlecStrong** [JetBrains/Grammar-Kit#239]
i have a grammar rule like so:

```
expr ::= ( raise_expr
         | other rules
         | binary_or_expr
         | binary_and_expr
         | between_expr
         | other rules
)
```

which is configured using `extends(".*expr")=expr` to enable prioritized parsing.

my `between_expr` rule looks like so:

```
between_expr ::= expr [ NOT ] BETWEEN expr AND expr
```

in the list of expressions it takes on priority 6 (it is the 7th rule). The generated code for expr_0 looks like this:

```java
 public static boolean expr_0(PsiBuilder builder_, int level_, int priority_) {
    ...
    while (true) {
      ... other rules
      else if (priority_ < 6 && between_expr_real_0(builder_, level_ + 1)) {
        result_ = report_error_(builder_, expr(builder_, level_, 6));
        result_ = between_expr_real_1(builder_, level_ + 1) && result_;
        exit_section_(builder_, level_, marker_, BETWEEN_EXPR, result_, true, null);
      }
      ... other rules
}
```

the issue is that `between_expr_real_1` looks like this:

```java

  // AND expr
  private static boolean between_expr_real_1(PsiBuilder builder_, int level_) {
    if (!recursion_guard_(builder_, level_, "between_expr_real_1")) return false;
    boolean result_;
    Marker marker_ = enter_section_(builder_);
    result_ = consumeToken(builder_, AND);
    result_ = result_ && expr(builder_, level_ + 1, -1); // Here is the issue
    exit_section_(builder_, marker_, null, result_);
    return result_;
  }
```

when it recurses into `expr`, it has priority `-1`, and so it will start parsing rules with a lower integer priority than the between expression. I am able to resolve this by specifying the priority manually:

```
between_expr ::= expr [ NOT ] BETWEEN expr AND <<expr '6'>>
```

Apologies if that wasn't clear, took a while to understand it myself!

**Comment by gregsh** [comment]
You can use the following to address that more nicely:
```
expr ::= ... between_expr | the_next_expr ...
between_expr ::= expr [ NOT ] BETWEEN the_next_expr AND the_next_expr
```

**Comment by AlecStrong** [comment]
it's for SQLite, in the case I'm describing there's multiple expressions that follow between so I can't specify the next rule without copying a bunch. heres the actual source file for it: https://github.com/AlecStrong/sql-psi/blob/master/core/src/main/kotlin/com/alecstrong/sql/psi/core/sql.bnf#L171

**Comment by gregsh** [comment]
The next rule in your grammar would be `binary_like_expr`

**Comment by AlecStrong** [comment]
wouldn't that mean you can't use other expression types in the BETWEEN rule? or does `binary_like_expr` extending expression mean that the rule will also parse things below `binary_like_expr`?

**Comment by gregsh** [comment]
It acts as a min priority selector. So any rule with higher priority will be considered.
You can easily see it in the generated code.

**Comment by AlecStrong** [comment]
sweet! thanks for the help
