### ISSUE TITLE
GeneratedParserUtilBase breaks Liskov substitution principle

### ISSUE THREAD

**Issue by KarolRoman** [JetBrains/Grammar-Kit#241]
in `GeneratedParserUtilBase` class there are a lot of casts to `PsiBuilderImpl` or `Builder`. Lets consider one case without loss of generality:

```java
public static boolean isWhitespaceOrComment(@NotNull PsiBuilder builder, @Nullable IElementType type) {
    return ((PsiBuilderImpl)((Builder)builder).getDelegate()).whitespaceOrComment(type);
}
```

Based on method signature it accepts any implementation of `PsiBuilder` (what seems reasonable) but in code it assumes that it should be possible to cast it to `Builder` and then take internal delegate and cast it to `PsiBuilderImpl`.

Those casts prevent to provide own implementation of `PsiBuilder`.

I understand that `PsiBuilder` does not expose all capabilities to implement this kind of method but in such case:
 * Would it not be better to extend `PsiBuilder` interface with additional methods?
 * Or would it not be better to change signature of `isWhitespaceOrComment` method to:
```java
public static boolean isWhitespaceOrComment(@NotNull PsiBuilderImpl builder, @Nullable IElementType type)
```

**Comment by gregsh** [comment]
`GeneratedParserUtilBase` is not an API *per se*, it is more of an engine. Grammar-Kit generator can supply any implementation via `parserUtilClass` attribute. I keep IntelliJ and Grammar-Kit versions in sync but one can copy any of them in own project and tweak to one's wishes.
