### ISSUE TITLE
Is there a new version of GrammarKit needed to resolve PSI issues with things like the Lombok Plugin?

### ISSUE THREAD

**Issue by dkowis** [JetBrains/Grammar-Kit#244]
Referencing https://github.com/mplushnikov/lombok-intellij-plugin/issues/840

I don't know what I'm doing around this stuff, and trying to figure it out.

Thanks!

**Comment by YannCebron** [comment]
GrammarKit is not involved in this problem

**Comment by dkowis** [comment]
Thanks!
