### ISSUE TITLE
Unable to use light-psi-all.jar in Gradle, getting java.lang.ClassNotFoundException: com.intellij.lang.ParserDefinition

### ISSUE THREAD

**Issue by hweigel528** [JetBrains/Grammar-Kit#245]
I'm trying to make a Standalone parser+compiler. Right now the gradle project depends on com.github.JetBrains:Grammar-Kit:2020.1

Tests are able to run the parser, but I'm failing to run the assembled and distributed java binary, thanks to: java.lang.ClassNotFoundException: com.intellij.lang.ParserDefinition

Something from the plugin SDK must be missing from the assembled classpath.

I suspect I would much rather have the light-psi-all.jar on my classpath than Grammar-Kit-2020.1.jar, but I do not know how to configure this in Gradle.

Is light-psi-all.jar accessible by Gradle in any way? Jitpack implies that this is the only jar associated with JetBrains/Grammar-Kit:
com/github/JetBrains/Grammar-Kit/2020.1/Grammar-Kit-2020.1.jar

So I'm not sure how to depend on the light-psi-all jar in a way which is idiomatic with Gradle.

**Comment by gregsh** [comment]
Please use https://github.com/JetBrains/gradle-grammar-kit-plugin.
