### ISSUE TITLE
Cannot navigate to interfaces listed in `implements = [...]`

### ISSUE THREAD

**Issue by fcurts** [JetBrains/Grammar-Kit#249]
In the following .bnf file, I can navigate to `foo.bar.Baz`:
```
foo ::= bar {
  implements = "foo.bar.Baz"
}
```

In the following .bnf file, I cannot navigate to either `foo.bar.Baz` or `foo.bar.Qux`:

```
foo ::= bar {
  implements = [
    "foo.bar.Baz" 
    "foo.bar.Qux"
  ]
}
```

Grammar-Kit plugin 2020.1
IntelliJ IDEA Ultimate 2020.2.3

**Comment by gregsh** [comment]
Fixed by 723a6cbb4fa9ae9b264c902e41753dd41161fc7e, thanks.
