### ISSUE TITLE
Failed to download 'https://github.com/JetBrains/intellij-community/raw/master/tools/lexer/jflex-1.4/lib/JFlex.jar': handshake alert:  unrecognized_name

### ISSUE THREAD

**Issue by orac** [JetBrains/Grammar-Kit#25]
When I try to generate a lexer from an existing .flex file (with ctrl-shift-g), the plugin brings up a file chooser with the title, "Downloaded files will be copied to selected directory". There's no indication of what it's downloading, why it would need to download something, or where would be a sensible place to put it. After choosing a directory, I get the above error message.

I've tried choosing the root of my project directory, and tools/lexer/ and tools/lexer/jflex-1.4/ in the root of my existing checkout of the intellij-community source. I'm on IntelliJ IDEA 13.1.0.

**Comment by brizjin** [comment]
have same problem

**Comment by gregsh** [comment]
See #112 for help. The old JFlex is dropped.

**Comment by brizjin** [comment]
Gregsh, thank you, it helps! Install prerealise 1.3.1 version and if works now.
