### ISSUE TITLE
Generating parser code from bnf creates multiple @NotNull annotations

### ISSUE THREAD

**Issue by slideclimb** [JetBrains/Grammar-Kit#251]
As of Grammar-Kit 2020.3, the `generate parser code` action on a bnf file creates two `@NotNull` annotations in a lot of `Impl` class constructors. This results in an exception:

```
error: NotNull is not a repeatable annotation type 
public LatexParameterImpl(@NotNull @NotNull ASTNode node) {
```

Unfortunately, I have not been able to reproduce this behaviour anywhere else than the project where I encountered it, [TeXiFy-IDEA](https://github.com/Hannah-Sten/TeXiFy-IDEA). For example, it does not happen when running this action on the bnf in the [Simple language plugin example](https://github.com/JetBrains/intellij-sdk-code-samples/tree/master/simple_language_plugin). 

When generating the parser code on [Latex.bnf](https://github.com/Hannah-Sten/TeXiFy-IDEA/blob/master/src/nl/hannahsten/texifyidea/grammar/Latex.bnf) it generates, among others, the following constructor (for [LatexParameterImpl](https://github.com/Hannah-Sten/TeXiFy-IDEA/blob/master/gen/nl/hannahsten/texifyidea/psi/impl/LatexParameterImpl.java)):

```java
public LatexParameterImpl(@NotNull @NotNull ASTNode node) {
    super(node);
}
```
For TeXiFy, it does this in all `Latex...Impl` classes except `LatexCommandsImpl`, where the constructors are

```java
public LatexCommandsImpl(@NotNull LatexCommandsStub stub, @NotNull IStubElementType type) {
    super(stub, type);
}

public LatexCommandsImpl(@NotNull ASTNode node) {
    super(node);
}

public LatexCommandsImpl(LatexCommandsStub stub, IElementType type, ASTNode node) {
    super(stub, type, node);
}
```
as expected. This class is the only class that has a [Mixin](https://github.com/Hannah-Sten/TeXiFy-IDEA/blob/master/src/nl/hannahsten/texifyidea/psi/LatexCommandsImplMixin.java), which is the only difference I could find between this and the other classes/elements. I have no idea if this has something to do with it.

This behaviour did not exist in Grammar-Kit 2020.1, so I will downgrade to that version for now.

**Comment by gregsh** [comment]
Thanks, fixed. Feel free to grab the latest dev build.
As a workaround - use your own base element class instead of ASTWrapperPsiElement.
