### ISSUE TITLE
"Find Usages" does not find usages of a grammar symbol in the BNF

### ISSUE THREAD

**Issue by kaby76** [JetBrains/Grammar-Kit#255]
I'm trying to use the Grammar-Kit plugin to see how it works and record how to use it (the instructions in my opinion are inadequate).

After installing the Grammar-Kit plugin, I open [Grammar.bnf](https://github.com/JetBrains/Grammar-Kit/blob/master/grammars/Grammar.bnf) and start to peruse the grammar, which now has semantic highlighting, hover pop-up over a grammar symbol (_e.g., move the mouse so the cursor is over "rule_start" on line 64, and it will open a pop-up a window with the symbol, what appears to be the FIRST(rule_start) and FOLLOW(rule_start) sets for the symbol, etc._) In addition, I can right-click on a non-terminal "grammar_element" on line 54, select "Go to" => "Declaration or Usages" or "Implementation", and the cursor will be positioned at the beginning of "grammar_element" on line 59. So far, good.

I next want to see all the defining and applied occurrences of the non-terminal symbol "grammar_element" in the grammar, which is plainly on lines 54 and 59. I right-click on the "grammar_element" on line 54, and select "Find Usages". The editor now returns "Usages of grammar_element [:] Nothing found in 'Project and Libraries'". Well, obviously, there are two usages: the applied occurrence on line 54, and the defining occurrence on line 59 of the grammar. Why is it that "Go To Definition" finds the defining occurrence of the non-terminal, when "Find Usages" finds nothing, when there are two occurrences in the grammar?

This is pretty much unlike any editor of any language I've used for 30 years, and atypical of an extension for grammar editing.

**Comment by gregsh** [comment]
`Find Usages` feature takes two parameters: "what" to look for, and "where" (which is called "Scope" in IntelliJ).
The currently opened project and its dependencies (or "libraries") form a scope called "Project and Libraries".
That scope is often selected by default when `Find Usages` is invoked.

Given that, I guess what happened was: you opened some project, then opened the grammar file which was stored outside of the project, searched for "grammar_element" usages in "Project and Libraries" scope, and clearly there were none. To fix that either move the grammar file into the project or switch scope to "All Places" or "Current File".

Hope that makes things straight.

**Comment by kaby76** [comment]
Yes, that is how I opened the file (opened unrelated, far-removed project, then opened the .bnf file). If I just opened the file from the Welcome UI instead, the tool would have created a project and added the file to it, thus have a project scope. But, it's absurd. By your logic, "Go To Def" should not work because it also takes two parameters: what to look for (symbol at cursor) and where to look (the file the cursor is on). It finds the defining occurrence because "Current File" is the scope for that operation. Not great to be inconsistent, but "it's a feature". In any case, thanks for the explanation.

**Comment by gregsh** [comment]
`Go to Definition` works exactly as you described just with one addition - it always looks in the current file, then in a "Current Module and Its Dependencies and Some More" scope. `Go to Definition` and `Find Usages` are asymmetric in regards to a user. User usually wants to find any definition, but the `Find Usages` scope really depends on the task.

Two notes to the above:
1. I describe how IntelliJ Platform works and not how Grammar-Kit works.
2. I do agree that IntelliJ could have saved us some time by always mixing in "Current File" scope for files that are not in the current project. Feel free to create a usability problem report at https://youtrack.jetbrains.com/issues/IDEA and mention this discussion there.

**Comment by kaby76** [comment]
I'll skip on posting another issue. If this was implemented with an LSP server, the proper place for this implementation detail would be in the server because the server defines the scoping rules for a language, not the client. I do this with my own LSP server, and I plan on doing this in my server with a backend for Grammar-Kit [E]BNF files.
