### ISSUE TITLE
Regeneration of parser code with new version of GrammarKit led to broken parsing

### ISSUE THREAD

**Issue by MikhailShumenko** [JetBrains/Grammar-Kit#258]
Looks like some features were missed in the new version, could you advise how to return them back?

This broke parsing for "injected" fragments. How to return previous behavior for the generator?

<img width="1440" alt="Screenshot 2021-02-20 at 01 08 29" src="https://user-images.githubusercontent.com/4786289/108571285-87d19200-7318-11eb-96a3-f2f030fc977a.png">

<img width="1440" alt="Screenshot 2021-02-20 at 01 12 12" src="https://user-images.githubusercontent.com/4786289/108571353-afc0f580-7318-11eb-9222-67e081a62032.png">

**Comment by gregsh** [comment]
Use `extraRoot=true` attribute for the required rules.
"Implicit" grammar root rules were replaced by an explicit way to specify that to reduce clutter.
