### ISSUE TITLE
can't use lookahead in .flex file

### ISSUE THREAD

**Issue by pikachuabc** [JetBrains/Grammar-Kit#263]
PREDICATE=(([:lowercase:])|_)(([:letter:]|[:digit:])|_|-|:)*/\(

this is a regex I wrote for matching function name, i get compile error on / , according to jflex manual, there are $ and / avaiable for lookahead

**Comment by gregsh** [comment]
JFlex file syntax is
```
UserCode
%%
Options and declarations
%%
Lexical rules
```

> PREDICATE=(([:lowercase:])|)(([:letter:]|[:digit:])||-|:)*/(
That is a declaration, not a rule.

Lookahead is allowed in the rules section, not in the declarations section.
See https://jflex.de/manual.html
