### ISSUE TITLE
how to fix jflex jar download error

### ISSUE THREAD

**Issue by ClarkWoo** [JetBrains/Grammar-Kit#264]
After I click the menu "run jflex generator", occur the error "JFlex jar not found: Create global library with jflex-xxx.jar and idea-flex.skeleton file to fix", how to handle this error? What are the location of jflex jar and idea-flex.skeleton i should put

**Comment by gregsh** [comment]
I've changes the download link to the new one:
```
https://cache-redirector.jetbrains.com/intellij-dependencies/org/jetbrains/intellij/deps/jflex/jflex/1.7.0-2/jflex-1.7.0-2.jar
```

**Comment by ClarkWoo** [comment]
It works. Thanks!

**Comment by bardiharborow** [comment]
This appears to have regressed on 2022.3.2.

**Comment by YannCebron** [comment]
The action works for me with 2022.3.2 plugin.
Please verify you can access URL
https://cache-redirector.jetbrains.com/intellij-dependencies/org/jetbrains/intellij/deps/jflex/jflex/1.9.2/jflex-1.9.2.jar

Try removing "JFlex" library in _Project Structure | Global Libraries_ as well.

**Comment by YannCebron** [comment]
@gregsh please take a look
