### ISSUE TITLE
[Question] How to treat downloaded files (flex*.jar and idea-flex.skeleton) in the project under VCS?

### ISSUE THREAD

**Issue by ileasile** [JetBrains/Grammar-Kit#265]
Plugin suggests a current project directory for them by default, but I'm not quite sure it's the right place for them because their destination is saved somewhere in plugin settings and stays the same for all the projects where I use it.

Should I commit these files or ignore them? Or better put them somewhere outside the project? Can I make their location project  (not application) specific?

**Comment by gregsh** [comment]
Downloaded JFlex lib jar is stored in Project Structure `(Platform Settings) | Global Libraries`.
It makes no sense to commit those files to VCS.
