### ISSUE TITLE
Custom parsing errors

### ISSUE THREAD

**Issue by BossyRomain** [JetBrains/Grammar-Kit#268]
Hy,

I'm making a custom language support plugin and i'm actually defining the grammar of the language but i don't know how to generate custom errors when a token is missing.

Could you help me please ?

**Comment by hurricup** [comment]
For rule like:
```
rule ::= TOKEN_A TOKEN_B 
```
You may do:
```
rule ::= TOKEN_A subrule {pin=1}
private subrule ::= TOKEN_B {name='some semantic token name'}
```
In such case when `TOKEN_B` is missing you will get `'<some semantic token name> expected`.
IRR you can't specify exact message.
