### ISSUE TITLE
Need some suggestions

### ISSUE THREAD

**Issue by ethdev1** [JetBrains/Grammar-Kit#269]
Sorry for opening this as an issue.

I'm trying to write a rule for the optional semicolons, and trying to wrap my head around the best way to do this.

---
Single import with no semicolon - **Valid**
`
import "hello"
`

Single import with a semicolon - **Valid**
`
import "hello";
`

Multiple imports with no semicolons - **Invalid**
`
import "hello"
`
`
import "hi"
`
`
import "bye"
`

Multiple imports with semicolons - **Valid**
`
import "hello";
`
`
import "hi";
`
`
import "bye";
`

Multiple imports with _no semicolon on the last import_ - **Valid**
`
import "hello";
`
`
import "hi";
`
`
import "bye"
`

---

The best I come up with is the following, but this doesn't meet all the cases. Basically, the semicolon is optional on final import statement. 

`imports ::= import (';' import)*`

Really appreciate if anyone can give me a suggestion the best way to do this :)

**Comment by jvolkman** [comment]
Just add an optional semicolon at the end: 
```
imports ::= import (';' import)* ';'?
```

**Comment by ethdev1** [comment]
> Just add an optional semicolon at the end:
> 
> ```
> imports ::= import (';' import)* ';'?
> ```

Why didn't I think of that  :dancers: 

Thank you

I'll close the issue.
