### ISSUE TITLE
Make a rule with an new line at the end

### ISSUE THREAD

**Issue by BossyRomain** [JetBrains/Grammar-Kit#270]
I want to make a rule where i can put all my types of tokens but when the parser reach a new line it start an new expression.

For example : 
rule a ::= (Tokens)+ END_OF_LINE

How can i make it please.

**Comment by hurricup** [comment]
You should lex such new lines as some separate token type. And this type should not be included to spaces set, returned by your parser definition.

**Comment by RomainBossyStandUser** [comment]
Is it possible to use TokenType tokens in the grammar ?

**Comment by hurricup** [comment]
I'm not sure I understand your question. 

Spaces and comments are skipped by the parser. you can't use them in rules.

**Comment by RomainBossyStandUser** [comment]
Ok thanks so can i use a Psi methods during the parsin to cut my conditions in smaller conditions blocks ?

Like if i have this one condition : 
@test = 123
$test = "test"
the method will return to conditions : 
1 - @test = 123
2 - $test = "test"

**Comment by hurricup** [comment]
Technically yes, you may use `rawLookup` methods to achieve this. But I would not recommend this approach. Proper lexing seems better. 
Btw, you may keep lexing the same, but produce zero-length pseudo-semicolon elements before each newline. You will be able to use them in parser and they won't make it to the resulting tree

**Comment by RomainBossyStandUser** [comment]
i found a solution. When i annotate errors on condition i make a list of sub conditions separate by a whitespace with a new line inside. Then i check the errors on those sub conditions.

**Comment by hurricup** [comment]
I have no idea what are you saying :)
