### ISSUE TITLE
Toy grammar fails with recoverWhile

### ISSUE THREAD

**Issue by LivingPages** [JetBrains/Grammar-Kit#271]
I am struggling with getting recoverWhile to work.

It doesn't work in my language or a slightly more elaborate syntax than JSON. So, I created a toy grammar to nail the problem down. Actually 3 months ago, but nobody wanted to help: :(

- [IntelliJ Support](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360010539720-Grammar-Kit-toy-grammar-fails-with-recoverWhile?page=1#community_comment_360003208640)
- [JetBrains Youtrack](https://youtrack.jetbrains.com/issue/IDEA-264347)

This is the toy grammar:

```
{
  tokens = [
    id = "regexp:\p{Alpha}\w*"
    eq = "="
    colon = ":"
    brace1 = "{"
    brace2 = "}"
  ]
}
value           ::= id | object
object          ::= '{' (prop | expr) '}'
prop            ::= id ':' value             {pin = 2 recoverWhile = recover}
expr            ::= id '=' id
private recover ::= !( ':' | '=' )
```

This is tried with the following **valid** syntax:
```
{a=b}
```
But Grammar-Kit flags it as invalid (at the position of '='). The recoverWhile expression may be incorrect, but whatever I try to correct it, I always obtain an invalid flag. Only deleting the recoverWhile expression helps. But of course, then the pin feature becomes useless.

Before I claim a bug: Is there any way to get the above example to work at all?

Is there any documentation which explains how pin does actually work (none of the three .md documents does).?

As a more mortal cannot currently use recoverWhile in grammar-kit, and therefore, cannot add language support to IDEA, I declare grammar-kit broken.

Kind regards,
Falk

**Comment by LivingPages** [comment]
Note: I initially had a star-notation to have an iterative grammar (like `value ::= id | object*`. But it didn't seem to work too.

**Comment by gregsh** [comment]
The reasoning is simple, rules are applied left-to-right, top-to-bottom, keeping in mind that **recovery takes place regardless of the matching result**.

So:
1. `{` matched ok
2. trying `prop`, matching `id` but then failing on `:` (we expect `=`)
3. rolling back to `id` and skipping back to the last error pos, which is `=`, reporting the error here, and try to run recovery further but failing because of `!'='` (it's a bit complicated here)
4. that's it

Writing a grammar with a good error recovery is hard. The kinds of incorrect sequences you try to handle dictate the form of the recovery you shall employ.

For example, if you want to handle `zzz` as an error in `{a=b zzz}` you shall move the recovery to `expr` as follows:

```
prop            ::= id ':' value             {pin = 2}
expr            ::= id '=' id                {recoverWhile = recover}
private recover ::= !( id | '}')
```

**Comment by LivingPages** [comment]
Hi Grep,
thanks for your help. I can confirm that the modified grammar now parses `{a=b}` w/o error. It parses `{a:{b:{b:{b:{b=c}}}}}` too. So, I assume that grammar-kit isn't broken after all.

I'll try to work a deeper understanding, based on the few words you gave me. I still think that lecture notes are required to get outside people master your tool when it comes to error recovery (Isn't there any material you shared with co-workers to get them started?). I knew how Grammar-Kit grammars are programs. And still ...

Thanks again, Falk

**Comment by jvolkman** [comment]
You might also try looking at and stepping though the generated parser
code. In my experience it's fairly straightforward.

**Comment by Terrency** [comment]
``` grammar
{
  tokens = [
    id = "regexp:\p{Alpha}\w*"
    eq = "="
    colon = ":"
    brace1 = "{"
    brace2 = "}"
    bl = '('
    bl2 = ')'
    cal = '-'
  ]
}
value           ::= id | object | prop |  calc
object          ::= id '=' id
prop            ::= id '(' value ')'
calc            ::= id '-' id
```
i use this grammar to match ```a=b```, but it failed, this is Parsing Expression Grammar diff with Contex free grammar problem, i can only change value rule to ``` value ::= object | prop | calc | id```
and is there any other way to make it work?
