### ISSUE TITLE
using space as a seperator

### ISSUE THREAD

**Issue by Shuaiouke** [JetBrains/Grammar-Kit#274]
Im trying to make a custom language that uses space to separate the key and value like

HelpMessage This is an example help message

but from what i can find online, lexer does some stupid things and just doesn't pass the space to the parser or something. is there a way to overwrite this behavior?

**Comment by hurricup** [comment]
Similar recommendations as in #270

**Comment by Shuaiouke** [comment]
I have seen issue #270 but I do not understand what they're saying, can you please explain? Is the suggestion to use external classes as that bypasses it?

**Comment by hurricup** [comment]
Your lexer should produce different tokens for meaningful spaces. And you should handle them in your parser. Regular spaces and comments are ignored by parser. They are defined by `com.intellij.lang.ParserDefinition#getWhitespaceTokens` and `com.intellij.lang.ParserDefinition#getCommentTokens`

**Comment by Shuaiouke** [comment]
I think I understand what you are saying now, but I still dont know what I should do regarding this, do I change the type of whitespace inside of my definition?

**Comment by hurricup** [comment]
No. you define your own token for spaces and use it in your lexer in appropriate places.
Your lexer file (.flex) should be adjusted and it should be smarter than auto-generated regexp matcher. It should distinct where space is space and where is not. E.g.:

**Comment by Shuaiouke** [comment]
So I should be manually making a lexer? Are they not required to be updated with the bnf itself?

**Comment by hurricup** [comment]
@Shuaiouke auto-generated lexer can handle only simpliest cases. For more-less complicated language you need to make your own. And yes, it may be really tricky, depending on your language and on how smart you want to make it. 
Too smart lexers are good for highlighing in general, but may be slower for general and incremental lexing. Also, it may duplicate some parser logic. 
E.g. here is my perl5 lexer: https://github.com/Camelcade/Perl5-IDEA/blob/master/plugin/core/grammar/Perl.flex

**Comment by Shuaiouke** [comment]
I think Im starting to understand, but still confused on the structure of the lexer
is it like

<Actual string that user typed in> {RETURN <What Would Be Reported To the Parser>}?

**Comment by Shuaiouke** [comment]
@hurricup is there a document regarding the structure of the flex file? Or maybe a less complicated example? Your own lexer is too long for me to understand and is hurting my brain

**Comment by hurricup** [comment]
No. 

Simplified process is:

1. Lexer takes text and produces text ranges with types using rules and states described in flex file. Basically - splits texts into words and marks them with different meaning (token types). 
2. Parser takes tokens list and build an AST tree using rules described in BNF. 

E.g.:
1. We have a text: `something = otherthing`
2. Lexer will produce: `identifier_token, space_token, equal_token, space_token, identifier_token` (it will also produce ranges in text, but it doesn't matter here)
3. Parser will eat what lexer produced and will build something like:
```
assign_expr
   target
      identifier_token
   equal_token
   source
      identifier_token
```

This flex generation from bnf is a nice shortcut, suitable for simple cases. 

Lexer is basically is a [FSM](https://en.wikipedia.org/wiki/Finite-state_machine) described in flex file. You match rule and may produce a token, change state or just do nothing. 

Here is jflex documentation: https://www.jflex.de/docu.html
This may be helpful too: https://plugins.jetbrains.com/docs/intellij/custom-language-support.html

**Comment by Shuaiouke** [comment]
So in this case, inside of the lexer is something like
IDENTIFIER=\w+

%%
<YYINITIAL> {

IDENTIFIER { return identifier_token}

' ' { return space_token }

etc

and parser will be dealing with *_token correct?

**Comment by Shuaiouke** [comment]
Wait so the whole tokens=[] part is not needed at all since you can do everything in the lexer right? the tokens=[] part is just for generating the automatic one?

**Comment by hurricup** [comment]
You may omit them, yes. In this case GK will generate those from bnf file. But I prefer to define them explicitly and give them some nice names, like here https://github.com/Camelcade/Perl5-IDEA/blob/0de4e4b53d1b8c4b3b68f33d3fac2890191e61a7/plugin/core/grammar/Perl5.bnf#L124

These names gonna be used in error messages. Otherwise you may see things like: `Unexpected token, RESERVED_TOKEN, SOMEOTHER_TOKEN expected, got....` instead some nice `Unexpected token, if, else or end expected, got ...`

**Comment by Shuaiouke** [comment]
the tokens are given to the parser through return if Im understand it correctly?

**Comment by hurricup** [comment]
in a simple way  - yes. As i described before 

text -> |lexer| --- tokens --->  |parser| -> AST

**Comment by hurricup** [comment]
Here is the properties plugn, it was helpful when I started to work on perl plugin. https://github.com/JetBrains/intellij-community/blob/master/plugins/properties/src/com/intellij/lang/properties/parsing/Properties.flex

Also other open-source plugins may be really useful.

Also, from my experience - write tests for parser. From start. Makes your life easier.

**Comment by Shuaiouke** [comment]
I see, I guess I'll have to nuke all my of my bnf code and start again now.

**Comment by hurricup** [comment]
@Shuaiouke did this 3 times before current state. As Rick said: https://www.youtube.com/watch?v=3uAQeVExWJk

**Comment by Shuaiouke** [comment]
What do I do if there's multiple Tokens with the same definition but I want to have different help messages?
like Hook and Help both wants a string to follow, but I want one to be HookName expected and the other one to be HelpMessage Expected
Also is there any chance that I can have spaces in the token names?

**Comment by hurricup** [comment]
yes, you may use spaces.
GK will generate error messages for you basing on your rules, rules names and tokens texts. You'll see. I suggest you not to worry about exact messages for now. you may address this later.

**Comment by Shuaiouke** [comment]
Ok thanks, one more question and Ill close the issue, is there any way I can contact you personally if I have any more questions or should I just use the issue system.

**Comment by hurricup** [comment]
Sounds like we should enable github discussions for this project for this. What do you think, @gregsh ?

**Comment by YannCebron** [comment]
Please use Forum or Slack channel for plugin development questions. Many other plugin developers hang out there and can help you https://plugins.jetbrains.com/docs/intellij/getting-help.html

**Comment by Shuaiouke** [comment]
I want to use slack but Im having some problems with it, one is that I dont get replies as fast as github, and the second thing is i registered on my phone and it never asked for my email, so now i can't log in on my PC because I dont have any email for my account, so then I would have the type my problems with my phone which is less than ideal

**Comment by YannCebron** [comment]
I don't see any user with your GH username there. I suggest you signup again.

**Comment by Shuaiouke** [comment]
Yeah thanks, I got it, my name on slack is Eric :D
