### ISSUE TITLE
Different tokens even with the same regex?

### ISSUE THREAD

**Issue by Shuaiouke** [JetBrains/Grammar-Kit#275]
Heyall, so I played around a bit with the lexer, and I think I know what it does now, but there's a problem Im facing, I know there must be a solution out there, but I just haven't found one yet: have the lexer return different tokens depending on the context (or something)
so if I do something like
Property '=' Value in the bnf, but i want both of them to be a word (\w+)
I would need the lexer to return different tokens for the same input, how does one do that?

**Comment by hurricup** [comment]
https://github.com/JetBrains/Grammar-Kit/issues/274#issuecomment-866959982

**Comment by Shuaiouke** [comment]
should I continue the issue or?

**Comment by hurricup** [comment]
No. You should ask on the dev support forum as requested. This tracker is for grammar-kit bugs/features request, not usage help.
Also, your question was answered: https://github.com/JetBrains/Grammar-Kit/issues/274#issuecomment-866825846
