### ISSUE TITLE
Misplaced nullability annotation for method return type in generated classes

### ISSUE THREAD

**Issue by stoyanovskiy239** [JetBrains/Grammar-Kit#281]
According to the current `intellij` code style `@Nullable` and `@NotNull` should be placed as `TYPE_USE` annotations.

#### Expected
```
@Override
public @NotNull ReturnType methodName() {...}
```

#### Actual
```
@Override
@NotNull
public ReturnType methodName() {...}
```

**Comment by gregsh** [comment]
Shall be fixed since 5e307843044965bb8cf57a2852f62382e61c7ed8. Please comment if it isn't.
