### ISSUE TITLE
Who knows the BNF's syntax?

### ISSUE THREAD

**Issue by f1024557668** [JetBrains/Grammar-Kit#285]
I want to write a plugin about the language tool,but the document's demo was too simple.I need to know more about the BNF.Is there anyone give me a hand?

**Comment by hurricup** [comment]
You may check docs in this repo, check bnf grammars in other plugins. People may answer specific questions on plugin dev forum: https://intellij-support.jetbrains.com/hc/en-us/community/topics/200366979-IntelliJ-IDEA-Open-API-and-Plugin-Development

don't know anyone who could teach you to write bnf from scratch.

**Comment by YannCebron** [comment]
here is list of OSS plugins implementing custom language, nearly 99% of them use GrammarKit these days https://plugins.jetbrains.com/intellij-platform-explorer?extensions=com.intellij.lang.parserDefinition

also, IntelliJ Community sources has plenty of `.bnf` files to browse
