### ISSUE TITLE
[Question] BNF parser generation with wrong import

### ISSUE THREAD

**Issue by javatlacati** [JetBrains/Grammar-Kit#294]
When you generate a parser form a BNF file e.g when following [custom language tutorial](https://plugins.jetbrains.com/docs/intellij/grammar-and-parser.html).

it generates 

    import com.intellij.lang.parser.GeneratedParserUtilBase.*;

in the parser file and I think it should be

    import static org.intellij.grammar.parser.GeneratedParserUtilBase.*;

can you confirm?

**Comment by gregsh** [comment]
Just tried to reproduce. The tutorial grammar parser for me shows `import static com.intellij.lang.parser.GeneratedParserUtilBase.*;`.
