### ISSUE TITLE
When clicking on "Run JFlex Generator" it appears that it cannot be downloaded

### ISSUE THREAD

**Issue by Heliecp** [JetBrains/Grammar-Kit#300]
When I follow the steps in the Custom Language Support Tutorial in Part VII - Custom Languages of the IntelliJ Platform SDK DevGuide under 4. Lexer and Parser Definition, the following problem occurs.
[![xA2KGn.png](https://s1.ax1x.com/2022/09/24/xA2KGn.png)](https://imgse.com/i/xA2KGn)
As my English is not very good, please understand that I have chosen translation software to translate these texts!

**Comment by wuhuagang** [comment]
I have the same problem，Browsers don't seem to be able to access the address either（https://raw.githubusercontent.com/JetBrains/intellij-community/master/tools/lexer/idea-flex.skeleton）
![image](https://user-images.githubusercontent.com/26036255/226110797-4ec1727e-7dbf-4ccb-ac72-d0707e2f2c49.png)
