### ISSUE TITLE
Possibility of generating separate classes for holding stub and non-stub element types

### ISSUE THREAD

**Issue by karollewandowski** [JetBrains/Grammar-Kit#314]
According to the `StubElementTypeHolderEP` doc:

> To speed up IDE loading, it's recommended that this extension is used for interfaces containing only IStubElementType (or ObjectStubSerializer) constants, and all other language's element types are kept in a separate interface that can be loaded later.

Source: https://github.com/JetBrains/intellij-community/blob/master/platform/core-api/src/com/intellij/psi/stubs/StubElementTypeHolderEP.java#L17:L26

Currently, it doesn't seem possible to have separate element type holder classes for stub and non-stub element types when parser is generated with Grammar-Kit.

**Comment by gregsh** [comment]
GK does not generate that `StubElementTypeHolder` interface with all the constants but it is possible to create it manually.

See [GroovyStubElementTypes](https://github.com/JetBrains/intellij-community/blob/master/plugins/groovy/groovy-psi/src/org/jetbrains/plugins/groovy/lang/parser/GroovyStubElementTypes.java#L7). There it just collects all stub element types from the generated `GroovyElementTypes`.

The indexing subsystem uses the EP to collect constant names without initializing them.

**Comment by PHPirates** [comment]
I see, so we just have to keep that file up to date manually, thanks!
