### ISSUE TITLE
Uncompilable code in generated parser

### ISSUE THREAD

**Issue by pjonsson** [JetBrains/Grammar-Kit#32]
I get a compilation error in my parser from the following code:

``` verbatim
import ::= var
         | tycon ["(..)" | cnames]
         | tycls ["(..)" | vars]
```

Renaming "import" to "importt" makes the problem go away. The generated java Parser contains a function called "import".

**Comment by gregsh** [comment]
Keywords are now transparently escaped like `import_$`
