### ISSUE TITLE
Generator drops zzAtBOL and zzEOFDone from code and makes lexer non-compilable

### ISSUE THREAD

**Issue by jreznot** [JetBrains/Grammar-Kit#332]
![image](https://user-images.githubusercontent.com/1066152/229310951-cc2cea2f-00df-40d4-a93b-0da5682e6719.png)

![image](https://user-images.githubusercontent.com/1066152/229311000-5f160aa2-d0b3-4e40-92a1-f4b484eae7f2.png)

Reproduced on https://github.com/jreznot/jdl-intellij-plugin

See `src/main/grammar/jdl.flex` and run Generate Lexer.

IntelliJ IDEA 2023.2 Nightly

**Comment by jreznot** [comment]
There is no such problem in 2023.1 but nightly is affected

**Comment by hurricup** [comment]
my guess is that skeleton is downloaded from IJ commmunity and skeleton there is updated to 1.9.1

**Comment by hurricup** [comment]
#325 need to be released to fix this. Atm seems only gradle plugin works properly.

**Comment by goto1134** [comment]
@gregsh , reproduced this bug on 2023.2.4 and 2024.1 Nightly
