### ISSUE TITLE
Can we use ranges (like `[0-9]`) in .bnf files with Grammar Kit?

### ISSUE THREAD

**Issue by chriskilding** [JetBrains/Grammar-Kit#352]
When writing grammars we frequently want to use ranges (such as `[a-z]` or `[0-9]`) for conciseness. This appears to be supported in some grammar tools, like [BNF Playground](https://bnfplayground.pauliankline.com), so it appears to be valid BNF.

When I tried writing a .bnf file containing a range in the latest IntelliJ / Grammar Kit plugin (2023.2.3), I get an error:

`<<, <literal expression>, <paren expression>, <predicate>, <quantifier>, '[' or id expected, got '-'`

But I have also had spurious errors from the Grammar Kit live preview on valid test strings, so I'm not sure whether the error is 'real', or whether it's just bugs in the plugin.

Are ranges supported by Grammar Kit in .bnf grammars? (For what it's worth they do appear to be supported in `.flex` files)

**Comment by gregsh** [comment]
GK grammars are parser only grammars. Not the parser and lexer grammars. GK-based parsers rely on external, possibly JFlex-based, lexers. 

There is no actual production lexing part in a GK grammar. Token definitions are just for fun with Live Preview, and they support ranges just like Java RegExps do. Token definitions are not used when a parser is generated.

Please see the (custom language support tutorial)[https://plugins.jetbrains.com/docs/intellij/custom-language-support-tutorial.html] in IntelliJ SDK docs.
