### ISSUE TITLE
How to write parser manually without using grammar-ki

### ISSUE THREAD

**Issue by alamhubb** [JetBrains/Grammar-Kit#356]
How to write parser manually without using grammar-kit? Are there any relevant examples?

https://plugins.jetbrains.com/docs/intellij/implementing-parser-and-psi.html#parser-implementation

![image](https://github.com/JetBrains/Grammar-Kit/assets/14007972/b498aaad-288f-47f7-9c54-a4e459b1255d)

**Comment by YannCebron** [comment]
There might still be some but it's not trivial to locate them in OSS plugins. 
In IntelliJ IDEA, Java plugin still uses manually written parser.

**Comment by alamhubb** [comment]
> There might still be some but it's not trivial to locate them in OSS plugins. In IntelliJ IDEA, Java plugin still uses manually written parser.

Thanks, but I didn’t find the Java plugin repository in github that you mentioned. Could you please paste its github address or other url link? I searched for java in the idea and only found these, but not the java plugin.

![image](https://github.com/JetBrains/Grammar-Kit/assets/14007972/3d3ea494-3a02-4734-b1dd-36cb982c5e1f)

**Comment by YannCebron** [comment]
See `java/java-psi-impl/src/com/intellij/lang/java/parser/`

**Comment by alamhubb** [comment]
> See `java/java-psi-impl/src/com/intellij/lang/java/parser/`

very thanks

**Comment by gregsh** [comment]
As you can see Grammar-Kit parsers mostly look like ordinary, recursive-descend, hand-written parsers. 

Differences:
1. The structure is more regular
2. Error recovery is extracted to `GeneratedParserUtilBase`.

**Comment by alamhubb** [comment]
> Two more: https://github.com/JetBrains/intellij-community/tree/idea/233.13135.103/plugins/properties/properties-psi-impl/src/com/intellij/lang/properties/parsing/PropertiesParser.java (very simple) https://github.com/JetBrains/intellij-community/blob/idea/233.13135.103/RegExpSupport/src/org/intellij/lang/regexp/RegExpParser.java (more complex)

thanks very much，I will study hard
