### ISSUE TITLE
expected token is the same got when preview bnf file 

### ISSUE THREAD

**Issue by minesunny** [JetBrains/Grammar-Kit#370]
I write some bnf rule and prview it；the error show that token expected is the same got；
![image](https://github.com/user-attachments/assets/8b632cd0-a6ce-4e17-be16-2a606533174a)
![image](https://github.com/user-attachments/assets/1d637732-8b4f-4473-9046-495a77a94dc5)

**Comment by thirteenthree** [comment]
I figure out that I create two symbol ';' using different ways. one ';' token defined with text token ,another ';' token defined with regex expression;
```
{
  tokens=[
    SEMI=';'
    EQ='='
    LP='('
    RP=')'

    space='regexp:\s+'
    comment='regexp://.*'
    number='regexp:\d+(\.\d*)?'
    id='regexp:\p{Alpha}\w*'
    string="regexp:('([^'\\]|\\.)*'|\"([^\"\\]|\\.)*\")"

    op_1='+'
    op_2='-'
    op_3='*'
    op_4='/'
    op_5='!'
    SEMI=';'
  ]

}
root ::= id SEMI semi_regex

semi_regex ::= 'regexp:;'
```

**Comment by karollewandowski** [comment]
I assume this is fixed on your side.
