### ISSUE TITLE
`Tools` -> `View PSI Structure` does not exist in IDEA 2024.2 (macos)

### ISSUE THREAD

**Issue by tsmock** [JetBrains/Grammar-Kit#374]
I'll note that it does exist when I run the IDE version that Grammar-Kit was developed against via `./gradlew runIde`, it does appear.

Additional notes: I'm using IDEA Ultimate edition build #IU-242.20224.419.

See https://plugins.jetbrains.com/docs/intellij/parsing-test.html#copy-the-expected-psi-tree .

**Comment by YannCebron** [comment]
You need to enable _Internal Mode_ explicitly https://plugins.jetbrains.com/docs/intellij/enabling-internal.html
