### ISSUE TITLE
Clear gen directory before generation

### ISSUE THREAD

**Issue by Alefas** [JetBrains/Grammar-Kit#57]
This is important, when you rename some rule. In this case previously generated Psi will be still in directory -> broken compilation, as visitor doesn't have some appropriate method.

**Comment by EBatTiVo** [comment]
Down-vote.  There are projects that have multiple grammars that all generate into the same directory.  Clearing /gen would force other, far more onerous, gymnastics to create a complete set.  An option to delete existing files would be OK, but then you can always do that by hand, too.

**Comment by Alefas** [comment]
Probably every generated source should contain comment with link to original file. Then before new generation we will need only to remove files with such mark.

**Comment by gregsh** [comment]
I'm totally agree with @EBatTiVo.

**Comment by Alefas** [comment]
@gregsh What about being totally agree with my answer? It's normal situation when generator can clean his generated files.

**Comment by gregsh** [comment]
@Alefas there're plenty of generators out there. One would probably use one 'gen' root for all kinds of generated stuff; parsers, flex lexers to name the few.
