### ISSUE TITLE
Live Preview reports error for Grammar.bnf

### ISSUE THREAD

**Issue by zielu** [JetBrains/Grammar-Kit#58]
Using 1.2.0.2 prerelease I tried "inception" scenario

1. Open Grammar.bnf
2. Open Live Preview
3. Paste Grammar.bnf content into Live Preview

PsiErrorElement: "{' unexpected'

**Comment by gregsh** [comment]
Same problem here. Explicit "whitespace" token is now required for LivePreview to work.

**Comment by gregsh** [comment]
Note that LivePreview does not support external rules, i.e. the following line shall replace the root rule definition:
````//grammar ::= grammar_element * // live preview root````

**Comment by liias** [comment]
should change the name space to WHITE_SPACE, so that "Run JFlex Generator" would not give an error about not existing rule.
