### ISSUE TITLE
Tutorial doesn't show real behaviour

### ISSUE THREAD

**Issue by tscheinecker** [JetBrains/Grammar-Kit#61]
I'm currently trying to figure out how the error recovery works and therefor i just copied the exmple given within [TUTORIAL.md](https://github.com/JetBrains/Grammar-Kit/blob/master/TUTORIAL.md).

The issue now is that the shown errors within the live preview don't match the ones expected.

![grammar_kit_error_recovery_issue](https://cloud.githubusercontent.com/assets/1931220/6842980/73d12056-d39e-11e4-9c92-97ef0dba40de.png)

After some digging in the code in the code I found that the actual test expects this behaviour:

[LivePreviewTutorial.txt#L56](https://github.com/JetBrains/Grammar-Kit/blob/master/testData/livePreview/LivePreviewTutorial.txt#L56)

So I dug some more, I found the following:

 - The screenshot in the tutorial is outdated and still shows `recoverUntil` instead of `recoverWhile` and also has the attribute at anoter element (*property* vs *root_item*)
 - The version used in the tests and in the tutorial text have a bad error recovery as I relly expected the error shown in the screenshot. This fixed the example for me:
```java
root ::= root_item *
private root_item ::= !<<eof>> property ';' {pin=1}

property ::= id '=' expr  {pin=2 recoverWhile=property_recover}
private property_recover ::= !(';' | id '=')
```

Maybe I'm on the wrong track and missed something obvious, but I would really appriciate it if the code in the tutorial, the screenshot and the test would match and convey the same thing.

If my solution sounds reasonable I'd be happy to help you out with a PR.
Just let me know.

**Comment by gregsh** [comment]
I've updated the screenshot, thanks!

The error reporting is changed but it is better the new way (see HOWTO on recoverWhile, esp. the placement part).

To correctly achieve the previous error reporting one need to tweak recover predicate as follows:

![screen shot 2015-03-26 at 21 06 19](https://cloud.githubusercontent.com/assets/958865/6853391/0189ce04-d3fc-11e4-8ea4-aae103f25441.png)
