### ISSUE TITLE
[question] How to implement resolve

### ISSUE THREAD

**Issue by gsouf** [JetBrains/Grammar-Kit#69]
Hello, I'm looking for implenting the resolve mehtod as explained here : https://confluence.jetbrains.com/display/IDEADEV/Developing+Custom+Language+Plugins+for+IntelliJ+IDEA#DevelopingCustomLanguagePluginsforIntelliJIDEA-ReferencesandResolve with grammar kit.

Any clue, or example explaining it ? 

Thanks!

**Comment by gregsh** [comment]
Grammar-Kit is PSI/Parser generator, no resolve automation is present.
To add custom resolve logic one can use method and class mix-ins described in

[HOWTO 3.3 and 3.4](https://github.com/JetBrains/Grammar-Kit/blob/master/HOWTO.md#33-implement-interface-via-implementation-mixin)
