### ISSUE TITLE
wrong consumption

### ISSUE THREAD

**Issue by masics** [JetBrains/Grammar-Kit#71]
bnf file:
```
{
  tokens = [
        space='regexp:\s+'
        line_comment="regexp://.*"
        block_comment="regexp:/\*(.|\r?\n)*\*/"
        simple_identifier='regexp:[a-zA-Z_][a-zA-Z0-9_$]*'
  ]
}

test ::= simple_identifier '=' binary_number ';'
binary_number ::= [ size ] "'" ( 'b' | 'B' ) binary_digit ( binary_digit )*
size ::= non_zero_decimal_digit ( decimal_digit )*
non_zero_decimal_digit ::= "1"| "2"| "3"| "4"| "5"| "6"| "7"| "8"| "9"
decimal_digit ::= "0"| non_zero_decimal_digit
binary_digit ::= '0' | '1'
```

test string:
qqq = 1'b1;

Error received: 
*B or b expected, got 'b1'*

Why it is trying to match more than 1 char?

Update: if you change test string to:
qqq = 1'b 1
(added space after 'b')
then parser does its job.

**Comment by masics** [comment]
Update: if you change test string to:
*qqq = 1'b 1*
(added space after 'b')
then parser does its job.

**Comment by gregsh** [comment]
See ````simple_identifier='regexp:[a-zA-Z_][a-zA-Z0-9_$]*'````. 
Lexer splits text into sequence of tokens.
Though '0' and '1' are matched-by-text sub-token parsing is not possible.

I advise to employ more clear separation of lexer & parser layers. "Binary number" is a perfect candidate for a lexer rule not parser.
