### ISSUE TITLE
Question about tokens in .bnf

### ISSUE THREAD

**Issue by gsouf** [JetBrains/Grammar-Kit#73]
Hi, I think I'm misunderstanding something about bnf and tokens, I'm trying to write a bnf file that will parse the following content : 

````
namespace aaaa;
````

I have tryed with the two bnf files bellow : 

````
{
  tokens = [
          space='regexp:\s+'
          identifier='regexp:[_a-zA-Z][a-zA-Z0-9_]*'
      ]
}

root ::= "namespace" identifier ";"
````

and 

````
{
  tokens = [
          space='regexp:\s+'
          identifier='regexp:[_a-zA-Z][a-zA-Z0-9_]*'

          NAMESPACE='namespace'
      ]
}

root ::= "namespace" identifier ";"
````

The first bnf works nice, while the second fails with the error ``namespace expected, got 'namespace'``

I wonder why it fails when I define the token ``NAMESPACE``, and I also wonder if I should define it here or not ? What's the exact purpose of these tokens ?
Because I'm using them as constant in the highlighter class or in the brace matcher.

Thanks !

**Comment by gregsh** [comment]
Order of tokens is important. It is good to move pattern-tokens to the end of the list.
