### ISSUE TITLE
Incorrect error reporting

### ISSUE THREAD

**Issue by endlos99** [JetBrains/Grammar-Kit#75]
This trivial grammar

    {
      tokens=[
        SEP=';'
        foo="foo"
        bar="bar"
        CRLF='regexp:\n'
        space='regexp:[ \t]+'
      ]
    }
    root ::= (stmt+ CRLF)*
    stmt ::= foo SEP bar SEP

applied to this text in LiveView

    foo ; bar foo ;

yields `PsiErrorElement: ";" unexpected`, even though it should be `foo unexpected` or "expected ; instead of foo".

**Comment by gregsh** [comment]
Fixed, thanks.
