### ISSUE TITLE
Publish to Maven repository

### ISSUE THREAD

**Issue by Turbo87** [JetBrains/Grammar-Kit#80]
It would be awesome if the JAR file was somehow distributed in some public Maven repository

**Comment by alexeykudinkin** [comment]
:+1:

**Comment by eprst** [comment]
Would also be great to relocate 3rd party packages to avoid conflicts, e.g. 
  -`com.google` → `gk.com.google`
  -`gnu` → `gk.gnu`
  -`org.picocontainer` → `gk.org.picocontainer`
  -`net.jcpi` → `gk.net.jcip`

Something like [ShadowJar](http://imperceptiblethoughts.com/shadow/#relocating_packages) can do this.

**Comment by matklad** [comment]
You can use jitpack.io:

```
repositories {
  maven { url 'https://jitpack.io' }
}

dependencies {
  compileOnly('com.github.JetBrains:Grammar-Kit:1.5.0') {
    exclude group: 'org.jetbrains.plugins'
  }
}
```

https://github.com/intellij-rust/intellij-rust/commit/e4ffb8d80b047966d8fe914c313c9f52db18c00b

**Comment by Turbo87** [comment]
jitpack.io actually seems like a good solution. thanks for that suggestion. closing this issue as somewhat solved.
