### ISSUE TITLE
JFlex 1.6.1: Reduce world entropy :)

### ISSUE THREAD

**Issue by aefimov** [JetBrains/Grammar-Kit#81]
Hello,

As you maybe know plugin JFlex Support does JFlex support as this plugin. If you can approve that your plugin is completely can be used over JFlex support, then i think that we must close JFlex Support to let users moving to this plugin.

/cc @ishchenko, @juzna, @lsf37, @sarowe 

I think, that we need to remove jflex-idea and replace it by this one plugin.

Thanks!

**Comment by sarowe** [comment]
Both plugins currently support JFlex 1.4.  

JFlex 1.5 was released almost in January 2014, and the current release is 1.6.1 - is there any plan to track new JFlex features in the Grammar-Kit plugin?

I'm (slowly) working on adding JFlex 1.6 support to jflex-idea.

**Comment by gregsh** [comment]
I've just checked [JFlex changelog](http://jflex.de/history.html).
Eventually the current state of things will be supported by Grammar-Kit.
