### ISSUE TITLE
Controlling binders in bnf

### ISSUE THREAD

**Issue by hurricup** [JetBrains/Grammar-Kit#91]
Would be really nice to specify binders in bnf options like
```
somerule ::= sometoken (, sometoken)+ {rightBinder=greedy_right}
```

**Comment by gregsh** [comment]
The feature somehow got its shape. Will release new version shortly.
'hooks' are general purpose "finally" handlers for low-level tweaking.

**Comment by gregsh** [comment]
Please note that hooks require the latest GeneratedParserUtilBase.
IntelliJ platform will have it since the next 2016.2 EAP. Workaround: use GPUB from Grammar-Kit.
