### ISSUE TITLE
Generated methods should not override PsiElement methods

### ISSUE THREAD

**Issue by carymrobbins** [JetBrains/Grammar-Kit#92]
Grammar-Kit generates the [HaskellCtype](https://github.com/carymrobbins/intellij-haskforce/blob/d2f2002e3444ff773aca75a27b857eb7209b1b0f/gen/com/haskforce/psi/HaskellCtype.java#L11-L11) interface, which has a `getContext()` method for getting the `HaskellContext` child node.  This method actually ends up overriding `PsiElement.getContext()`, which is used for something completely different.  This has caused a bug when other plugins use the `PsiTreeUtil.getContextOfType` method, creating an endless loop that halts the IDE.

See https://github.com/carymrobbins/intellij-haskforce/issues/228 for the related bug.

**Comment by gregsh** [comment]
One can use "methods" attribute to rename the generated method:
````
ctype ::= foralltype
        | contexttype
        | typee
{methods=[contextObj="context"]}

//will produce:
//HaskellContext getContextObj();
````

**Comment by carymrobbins** [comment]
So, you're right, but my point is that these generated methods probably shouldn't be overriding existing methods.  In this case, it was hard to track down and understand exactly what was going wrong and why.  If generated element accessor methods overlap existing methods in the PsiTree, an error indicating such might be useful to avoid bugs.  This could happen with any of the `get*` methods, like `getParent`, `getReference`, etc.
