### ISSUE TITLE
grammar error

### ISSUE THREAD

**Issue by seventh7me** [JetBrains/Grammar-Kit#94]
I wrote a simple grammar like below:
{
    tokens = [
        A = "regexp:[aA]{2}"
        COMMENT="regexp://.*"
        EOL="regexp:[\n|\r|\r\n]"
    ]
}

root ::= EOL* c? (EOL+ c)* EOL* {pin(".*")=1}
c ::= A {recoverWhile=recover}
private recover ::= !(EOL+)

I expect the whole document is filled with rule c, and each rule c is separated with \r\n. 
Following is a example:
<img width="462" alt="well" src="https://cloud.githubusercontent.com/assets/15548543/13201557/8a9d60f6-d8b1-11e5-81b2-ce8a100e1740.png">

But something strange happens when the document ends with \r\n as follows:

<img width="805" alt="bad" src="https://cloud.githubusercontent.com/assets/15548543/13201561/caaa6284-d8b1-11e5-9e39-a28c4a3a7042.png">

The preview shows me EOL is required, but EOL is just there.

**Comment by gregsh** [comment]
````
root ::= EOL* c? (EOL+ c)* EOL* {pin(".*")=1}
                  ^^^^ <--- EOL+ part is pinned
````

The pinned EOL+ is the reason for that error.

I'd fix that like that:
````
root ::= EOL* c? (spaces c)* EOL* {pin(".*")=1}
spaces ::= EOL + !<<eof>>
c ::= A {recoverWhile=recover}
private recover ::= !(EOL|A)

````

But as far as whitespaces are already treated in a special way by PsiBuilder I'd recommend just the following (recover predicate is much more correct here):
````
root ::= c *
c ::= A {recoverWhile=recover}
private recover ::= !A
````
