### ISSUE TITLE
Confused about left recursion

### ISSUE THREAD

**Issue by kravitz** [JetBrains/Grammar-Kit#95]
There is an inspection, which states, that left-recursion is unsupported. But on how-to pages you state, that "3. Use left recursion for binary and postfix expressions". If I try to write several left-recursive expression rules in a root rule I got an infinitie loop.

**Comment by kravitz** [comment]
Grammar is following

```
{
    parserClass="com.octaveide.parser.OctaveParser"
    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="Octave"
    psiImplClassSuffix="Impl"
    psiPackage="com.octaveide.psi"
    psiImplPackage="com.octaveide.psi.impl"

    elementTypeHolderClass="com.octaveide.psi.OctaveTypes"
    elementTypeClass="com.octaveide.psi.OctaveElementType"
    tokenTypeClass="com.octaveide.psi.OctaveTokenType"

    psiImplUtilClass="com.octaveide.psi.impl.OctavePsiImplUtil"

    tokens = [
        PLUS='+'
        MINUS='-'
        ASSIGN='='
        MULTIPLY='*'
        DIVIDE='/'
        SEMICOLON=';'
    ]

    extends("(assign|add|mul)_expr") = binary_expr
    extends(".*_expr")=expr
}

octaveFile ::= item_*
private item_ ::= !<<eof>> (statement|CRLF|COMMENT)

statement ::= expr (';'|CRLF|<<eof>>)

expr ::= add_group | primary_group

primary_group ::= literal | identifier

literal ::= int
    | float

add_group ::= plus_expr | minus_expr
plus_expr ::= expr '+' expr
minus_expr ::= expr '-' expr

fake binary_expr ::= expr+ {
    methods=[
        left="expr[0]"
        right="expr[1]"
    ]
}

private add_op ::= '+'|'-'

```

**Comment by kravitz** [comment]
I don't get why and where it is explained. But I got a special left recursion handling only after making sure, that all "expression groups" are private and every nearest public descendant of root expression rule ends with expr (as defined in extends)

**Comment by jvolkman** [comment]
That sounds about right. I agree that the conditions required to trigger the special expression logic are not well documented. From my understanding, this special logic kicks in when you've got one parent rule that consists solely of a choice between child rules that all extend the parent. By making your group rules private, they're removed from the rule structure and you end up with something like the following, which fits the required pattern.

expr ::= plus_expr | minus_expr | literal | identifier
plus_expr ::= expr '+' expr { extends = expr }
minus_expr ::= expr '-' expr { extends = expr }
literal ::= 'some_literal' { extends = expr }
identifier ::= 'some_identifier' { extends = expr }

**Comment by gregsh** [comment]
I tried to emphasise the expression logic in [HOWTO.md#2.4](https://github.com/JetBrains/Grammar-Kit/blob/master/HOWTO.md#24-compact-expression-parsing-with-priorities)
