### ISSUE TITLE
How does one change the path that lexer's generated Java file is generated into?

### ISSUE THREAD

**Issue by calexHG** [JetBrains/Grammar-Kit#96]
I recall it asking where to store it at one point, but how do I revise that?

**Comment by calexHG** [comment]
In place of a response, I'll answer my own question.

I got tired of of the lexer not being put into a generated files directory, and seeing as how no response was coming here, I skimmed through the plugin's source code. As it turns out, it doesn't look like the plugin does ever ask where to put it (what I thought I recalled might have been it asking where to download JFlex to, or where to find an existing JFlex). It uses its own heuristic to decide where to stick it, and that heuristic was choosing wrongly in my case. 

**If you want your generated lexer to go in the generated folder, and Grammar-Kit isn't doing that, it's because the way that GK is designed, your .flex file cannot be inside a source root.** Of course, the .flex file _is_ indeed a source file, but for GK's purposes it can't be marked that way — not if you want it to do the right thing and put its generated .java file into your designated generated folder.

Instead, **move your .flex file out of any source folders, and into a content root that is not marked as a source directory**. GK should now behave properly. For it's own source file, the .bnf file, it doesn't behave this odd way; only with the .flex file.

**Comment by gregsh** [comment]
Hey @calexHG 
I tried to use as little configuration as possible.
If one moves the generated file then it should be regenerated at that other place.

I've checked that the logic with IntelliJ community sources (available here on github): 
* moved  _GroovyLexer.java to some other root and edited it
* regenerated _GroovyLexer.flex
* checked that my new editing was discarded
So it kinda works right.

What's your layout?

**Comment by calexHG** [comment]
@gregsh Wow. Well, I certainly would never have expected it to be so intuitive as to automatically check if the generated file was in a different location from where it would have generated it, and then overwrite it at that different location! 

That's cool and fancy but maybe too fancy for its own good, as —speaking for myself at least— it's not yet ingrained as an expectation one has from their tools. So that logic goes to waste by people expecting a standard dumb generator and not taking advantage of that. (For example, in my case, I would never ever have just manually moved the generated file elsewhere, as with my thinking that would not have been a long-term solution and would have been thought to be a wasted action because every next time I generated the file, I would just have to manually move it again.) Instead, when I hear that from you, I'm surprised I haven't been bitten by that unexpectedly advanced logic yet. (As the dynamic path determination logic is unexpected, I may have moved a specific version of the generated file "out of harms way", to a different path so that it doesn't get overwritten and had surprising results.) In that way, smart undocumented behavior ends up being unused and potentially unintended behavior, so knowledge becomes key there. 

Anyway, my layout is as follows:

Root dir
- Source dir
  +- packagename
     +- LanguagenameGrammar.bnf
     +- lex
        +- LanguagenameLexer.flex
- gen

When I generate my parser’s generated Java file using this layout, the file properly ends up in `gen/packagename/Parsername.java`. However, when I generate the lexer’s generated Java file, it ends up in `src/packagename/LanguagenameLexer.java`. 
🤔

Hearing your perhaps overly advanced path logic, I suspect the bug may be that: it's entirely possible and in fact extremely likely that there was no `gen` folder the first time the lexer’s Java file was generated; GK didn't find one, and unlike all 4 other code generators I've used thus far in my limited handful of months using Java, it didn't create one; breaking what I thought was convention, it erroneously stuck my generated lexer in the source tree instead; and so during each following generation, whether the gen folder existed or not (which, eventually, it would have), it found the old generated lexer in the source tree, thought that was by the user's choice and erroneously stuck it there again? And then that erroneous path choice gets compounded by the user not knowing about the presumptive path logic behind it and assuming that if GK stuck it in the wrong place, it's because GK is statically programmed to stick it in the wrong place? I'm just theorizing here.. Does that sound like what’s probably happening? 

I come from other languages and have only been using Java since December, so it would be improper of me to speak with any authority about its conventions (maybe all the other four other code gen tools I've used), but it strongly seems like the path where things wrong here is that it seems GK might be deciding whether to put things in the the gen folder based on whether it was manually created and designated (or more likely automatically created by the stabdard tool that came before it) rather than automatically creating it itself?

**Comment by calexHG** [comment]
As a side note, I should mention that I think you're a genius and that any tool that operates at the level that something like Grammar-Kit or the tools that it abstracts, are marvels that they even work, and that technology and human comprehension allow some of us to even consider trying to automate the things you and I like to innovate on nowadays.

When such tools _are_ made, and they're released to the public, and they don't work the way people want it to, it will frustrate and create pain for them nonetheless. So, sorry if you ever wrongly take any critique from me or anyone else personally. They're not.

**Comment by gregsh** [comment]
I've unified the logic for BNF and Flex paths. Hope it'll become less confusing.

**Comment by Ramblurr** [comment]
@gregsh What is the logic? I am experiencing exactly the problem @calexHG reported on the latest version of GK. My parser code is generated into `gen/` but not the lexer.

**Comment by gregsh** [comment]
The logic was to seamlessly use GK "Run JFlex generator" action while working with IDEA project. There're lots of *.flex and corresponding generated java classes in various modules and folders.

**Comment by Ramblurr** [comment]
@gregsh When I first started using the generator it was generarting the parser and lexer into `gen/` and all was happy. Then I refactored my project layout a bit and now only the parser is going into `gen/`. Obviously I changed something.. any idea how I can get it back to generating into `gen/`?

```
src
└── com/
    └── outskirtslabs/
        ├── beancount/
        │   ├── BeancountLexerAdapter.java
        │   ├── Beancount.flex
        │   └── BeancountLexerUtil.java
        └── _BeancountLexer.java  <-----   ???? it's generated into my `src/` tree
gen
└── com/
    └── outskirtslabs/
        └── beancount/
            ├── parser/
            │   └── BeancountParser.java
            └── psi/
                └── impl/

```
