### ISSUE TITLE
Deal with unsupported/conflicting rule and token names in some way

### ISSUE THREAD

**Issue by calexHG** [JetBrains/Grammar-Kit#97]
When debugging, I somehow noticed that my naming of a subset of my rules with the naming pattern "*NameThatThisGroupOfRulesIsKnownAsToTheRestOfTheGrammar*_" (essentially just adding an underscore to the end of name of rules that used to implement other non-underscored names) might invisibly be causing errors in the logic, because the underscore, I think -- for some unknown reason -- isn't being carried over into the names of generated PSI classes and the generated code was thus likely unknowingly referencing one class when it thinks its referencing another class.

I say this was "likely" happening because I've run into too many subtleties like this when trying to use Grammar-Kit recently, so didn't want bother with wasting time thinking about it much more. So, I changed the naming pattern from an `_` at the end, to an `_Impl` at the end.

Unfortunately, I later detected that that was likely creating similarly unreported errors in the execution logic, for similar reasons: the underscore was being stripped (and thus my \*`_Impl` classes were probably getting referenced instead of the auto-generated \*`Impl` classes). At least, that's what half-a-second of headache-avoidance–reasoning lead me to be afraid of happening.

So, unfortunately, again, even though I don't think there should have been a conflict (because of the underscore), just to avoid invisible bugs potentially costing more hours/days of time, I unfortunately resorted to renaming my rules to something less readable and unfriendly — just because it seems that underscores aren't carried over.

If all of my caution was indeed warranted, **please either warn users when their rule names are unsupported, or work around their chosen rule names**. (Of course I expect you to choose the latter.)

**And less importantly: you shouldn't strip underscores from our rule and token names**. Is it doing this? Is there a reason it's doing this? Can you disable that, or allow us to disable that?

**Comment by gregsh** [comment]
There're several kinds of named artefacts:

* parsing functions
* elementType constants
* PSI classes and interfaces
* PSI methods

I've unified the code so that all processing goes through:
````
org.intellij.grammar.generator.ParserGeneratorUtil#toIdentifier
````

Now the generator doesn't strip leading and trailing underscores though some beatification and IntelliJ platform code-style is applied.

**Comment by calexHG** [comment]
Well, that's better than not... (and, indeed, that _was_ my original situation...)
:+1: 

I know about this behavior now, so I've adopted patterns that work around it, but I just don't see why it needs to be assertive about the naming the way it is. When trailing underscores didn't work, causing collisions, I moved to patterns that include embedded underscores with text suffixes. And when the embedded underscores were getting stripped, causing collisions, I changed the text suffixes. I just don't see why any of this is necessary, though, so long as they're all valid Java identifiers. o_0

According to the code, it looks like, in the case of class names, the code still strips embedded underscores; and in _all_ cases it will collapse _runs_ of underscores.

There are more important things, and it's not bothering me now, since I at least know how it works, but why the collapsing, and why strip at all in cases where it's clear the programmer explicitly intended to name something some way. The usage pattern already exists from the token side of the library (the token-case attribute): **why not maybe just support a `generate=[ class-case="as-is" ]` (truly as-is, though, for both classes and tokens and anything else used with it, meaning no underscore-run collapsing), putting it in the hands of the user how things get named, solving for all potential preferences in fell swoop?** Wouldn't that be both simple and ideal?

I'm currently much more involved with extracting better error handling out of this great starter tool you've gifted us, so this is rather low on my radar ATM ;]

In any case, you can't say I didn't offer my input!

thanks.

**Comment by calexHG** [comment]
...note, of course, that it seems a naming of "psi-case" would be more consistent.
