### ISSUE TITLE
Missing dependency for generated parser class

### ISSUE THREAD

**Issue by metadeus** [JetBrains/Grammar-Kit#99]
Trying to make standalone parser, but `import static com.intellij.lang.parser.GeneratedParserUtilBase.*;` is missing both in light-psi-all.jar and grammar-kit.jar. Any suggestions?

**Comment by gregsh** [comment]
add IntelliJ/lib/openapi.jar to dependencies
or specify the one from GrammarKit.jar as follows (global attribute):
````
parserUtilClass="org.intellij.grammar.parser.GeneratedParserUtilBase"
````

**Comment by metadeus** [comment]
Can I use the same BNF source for Intellij plugin and for standalone parser?
How should I deal with `com.intellij.lang.parser` vs `org.intellij.grammar.parser` in this case?

**Comment by gregsh** [comment]
There's no "vs". You can use any of those, or you can even copy GPUB to any package of your project.
